### ISSUE TITLE
Can't install image package

### ISSUE THREAD

**Issue by nwoodall** [octave-app/octave-app#11]
went to use a function in the image package and I got an error that suggested rebuilding the packages. That didn't help so I decided to install the latest package and the installation had errors about missing compiler support. Searched the web and supposedly this was fixed in version 2.6.1. So I downloaded version 2.6.1 and 2.6.2 and tried that and got the same errors. Also tried downloading the file and installing, and got the same errors. Running Mac osx Mojave (10.14). Doubled checked that Xcode was installed and up to date. I don't see any mention of problems on GNU Octave.

```
>> pkg install -forge image
configure: error: ** could not find a C++11 compiler
checking for a sed that does not truncate output... /Applications/Octave-4.4.0.app/Contents/Resources/usr/bin//gsed
checking for octave... /Applications/Octave-4.4.0.app/Contents/Resources/usr/Cellar/octave-octave-app_4.4.0/4.4.0/bin/octave-4.4.0
checking for mkoctfile... /Applications/Octave-4.4.0.app/Contents/Resources/usr/Cellar/octave-octave-app_4.4.0/4.4.0/bin/mkoctfile-4.4.0
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether clang++ -std=gnu++11 accepts -g... yes
checking for clang++ -std=gnu++11 option to enable C++11 features... unsupported
checking for clang++ -std=gnu++11 option to enable C++98 features... unsupported

pkg: error running the configure script for image.
error: called from
    configure_make at line 78 column 9
    install at line 184 column 7
    pkg at line 437 column 9
>> pkg list
Package Name  | Version | Installation directory
--------------+---------+-----------------------
       image  |   2.4.1 | /Users/nwoodall/octave/image-2.4.1
          io  |   2.2.3 | /Users/nwoodall/octave/io-2.2.3
  statistics  |   1.2.3 | /Users/nwoodall/octave/statistics-1.2.3
>> ver
----------------------------------------------------------------------
GNU Octave Version: 4.4.0 (hg id: d703d8bbc6ae)
GNU Octave License: GNU General Public License
Operating System: Darwin 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64
----------------------------------------------------------------------
```

**Comment by apjanke** [comment]
Okay, I can reproduce!

On 10.14.0, with Xcode installed from the app store, I get the following:

```
>> pkg install -forge image
configure: error: in `/var/folders/9k/7_hs3d7n15s7w7jv65_k5fs00000gn/T/oct-FrmTny/image-2.8.1/src':
configure: error: C++ compiler cannot create executables
See `config.log' for more details
checking for a sed that does not truncate output... /Applications/Octave-4.4.0.app/Contents/Resources/usr/bin//gsed
checking for octave... /Applications/Octave-4.4.0.app/Contents/Resources/usr/Cellar/octave-octave-app_4.4.0/4.4.0/bin/octave-4.4.0
checking for mkoctfile... /Applications/Octave-4.4.0.app/Contents/Resources/usr/Cellar/octave-octave-app_4.4.0/4.4.0/bin/mkoctfile-4.4.0
checking whether the C++ compiler works... no

pkg: error running the configure script for image.
error: called from
    configure_make at line 78 column 9
    install at line 184 column 7
    pkg at line 437 column 9
>>
```

That looks very similar to your error output.

If I do not have Xcode installed, then the error does not happen. (That is, it worked both before I had Xcode installed, and it worked again after I deleted Xcode.)

This one's gonna be fun, I can tell.

**Comment by apjanke** [comment]
Aha! After installing Xcode, did you manually run Xcode and agree to the license?

That's a necessary step in installing Xcode and getting it to work. After I manually ran Xcode and agreed to its license, this error went away for me.

**Comment by nwoodall** [comment]
I’m pretty sure that I did, I ran it and loaded a swift demo project.

For a variety of reasons, like having tried to use octave on the Mac every possible way, I decided to do a clean install. So that I’m sure all the modifications to those hidden files have been wiped out.

On Dec 4, 2018, at 11:21 PM, Andrew Janke <notifications@github.com<mailto:notifications@github.com>> wrote:


Aha! After installing Xcode, did you manually run Xcode and agree to the license?

That's a necessary step in installing Xcode and getting it to work. After I manually ran Xcode and agreed to its license, this error went away for me.

**Comment by apjanke** [comment]
Darn, I was hoping that was it.

Okay, when I find some spare time I'll fiddle around with it some more and see if I can reproduce it with a license-accepted Xcode.

Just to check, what do you get for the output of `xcode-select -p` and `which clang++`? For example, I get:

```
$ xcode-select -p
/Applications/Xcode-10.1.app/Contents/Developer
$ which clang++
/usr/bin/clang++
```

**Comment by nwoodall** [comment]
I didn’t bother with doing an xcode install, I’m not currently working on a project that requires it, so I just installed octave-app, then ran it. Complained about not having clang when I tried to install the package, the OS popped up a dialog box asked if I wanted to install command line tools, clicked okay and then it worked (note, the xcode app is not installed, I checked).


$ xcode-select -p

/Library/Developer/CommandLineTools

I’m pretty sure that it was leftover crap from previous Octave installations that was causing the problem. I just wasn’t comfortable manually fixing paths and removing leftover files.

**Comment by apjanke** [comment]
Okay, let's gather some additional information. Please download and run [this octave_app_diagnostic_dump.m script](https://github.com/octave-app/octave-app-bundler/blob/master/Mcode/octave_app_diagnostic_dump.m) and attach its output file to this issue.

**Comment by nwoodall** [comment]
I resolved the issue by doing a clean install of the Mac OS (there were other issues with respect to Microsoft products that I thought this would clean up too). As I mentioned previously, I had run Octave in the past using the X window system and with some of the other virtual machine implementations. So this would’ve eliminated all traces of the previous versions. Sorry I can’t be of more help on this.

Neil

**Comment by apjanke** [comment]
Okay, great. Chalking this one up to a hosed local configuration and marking as closed.

**Comment by mortezadmh** [comment]
> Okay, I can reproduce!
> 
> On 10.14.0, with Xcode installed from the app store, I get the following:
> 
> ```
> >> pkg install -forge image
> configure: error: in `/var/folders/9k/7_hs3d7n15s7w7jv65_k5fs00000gn/T/oct-FrmTny/image-2.8.1/src':
> configure: error: C++ compiler cannot create executables
> See `config.log' for more details
> checking for a sed that does not truncate output... /Applications/Octave-4.4.0.app/Contents/Resources/usr/bin//gsed
> checking for octave... /Applications/Octave-4.4.0.app/Contents/Resources/usr/Cellar/octave-octave-app_4.4.0/4.4.0/bin/octave-4.4.0
> checking for mkoctfile... /Applications/Octave-4.4.0.app/Contents/Resources/usr/Cellar/octave-octave-app_4.4.0/4.4.0/bin/mkoctfile-4.4.0
> checking whether the C++ compiler works... no
> 
> pkg: error running the configure script for image.
> error: called from
>     configure_make at line 78 column 9
>     install at line 184 column 7
>     pkg at line 437 column 9
> >>
> ```
> 
> That looks very similar to your error output.
> 
> If I do not have Xcode installed, then the error does not happen. (That is, it worked both before I had Xcode installed, and it worked again after I deleted Xcode.)
> 
> This one's gonna be fun, I can tell.

Hello,

I faced a similar issue today. I was using octave-cli. Another case where a similar error can happen is when you have installed Anaconda (Python). You would have to deactivate the base environment before you open the octave-cli app, otherwise, it may try using the clang version inside the Anaconda path (/Users/<userName>/anaconda3/bin/clang) instead of the one at /usr/bin/clang .

Good luck.
