### ISSUE TITLE
Switch to OpenBLAS

### ISSUE THREAD

**Issue by apjanke** [octave-app/octave-app#118]
The Octave maintainers seem to prefer, and mostly work with OpenBLAS as their BLAS implementation. Most don't use Apple's Accelerate veclib.

https://savannah.gnu.org/bugs/index.php?55534

There are behavior differences between veclib and OpenBLAS that cause some of the test suite to fail when using Accelerate.

Maybe switch Octave.app to OpenBLAS, to be more in line with "normal" Octave, and get a clean tests baseline.

The formulae to support this are all ready in https://github.com/octave-app/homebrew-octave-app-openblas.

**Comment by apjanke** [comment]
I can see one argument for sticking with Apple Accelerate: it keeps us consistent with core Homebrew's Octave builds. Since Homebrew is widely used, their Octave install base probably represents one of the largest Octave install bases, and thus maybe a good source of

I think the arguments in favor of switching to OpenBLAS are stronger, though: it's more important to be consistent with the larger Octave deployment base on Linux and Windows (and for that matter, the overall scientific computing community BLAS install base) than it is to be consistent with Homebrew. And the research/academic demand for open software stacks for reproducible research's sake is strong.

I've tentatively put this on the agenda for Octave.app 4.4.1-u2 and will start looking in to how to do this and whether there are other ramifications. Not committing to definitely doing it yet, though.

One thing to note: even though BLAS supports run-/load-time switching of your BLAS implementation without compiling, we don't have an easy tool for doing that run-time BLAS selection on Macs, especially with an app bundle like Octave.app where you can't easily set LD-related environment variables to take effect when you double-click the app icon.

**Comment by apjanke** [comment]
Hey, wait a minute: I just realized that the current core Homebrew `octave` is already using OpenBLAS instead of Apple Accelerate. So switching over would make us more uniform with just about everybody else.

```
$ ls -l /usr/local/bin/octave
lrwxr-xr-x  1 janke  admin  35 Sep 28 11:43 /usr/local/bin/octave -> ../Cellar/octave/5.1.0_6/bin/octave
[~/Downloads]
$ which octave
/usr/local/bin/octave
[~/Downloads]
$ octave -q
octave:1> version -blas
ans = OpenBLAS (config: OpenBLAS 0.3.7 DYNAMIC_ARCH NO_AFFINITY USE_OPENMP Haswell MAX_THREADS=3)
octave:2> exit
[~/Downloads]
$ brew info octave
octave: stable 5.1.0 (bottled), HEAD
High-level interpreted language for numerical computing
https://www.gnu.org/software/octave/index.html
/usr/local/Cellar/octave/5.1.0_6 (2,261 files, 53.8MB) *
  Built from source on 2019-09-28 at 11:43:48
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/octave.rb
==> Dependencies
Build: gnu-sed ✔, pkg-config ✔
Required: arpack ✔, [...], openblas ✔, [...]
```

Looks like this happened back in May of this year: 
* https://github.com/Homebrew/homebrew-core/pull/39809
* https://github.com/Homebrew/homebrew-core/issues/39226

And SciPy switched away from Accelerate to OpenBLAS in 2018:
* https://github.com/scipy/scipy/wiki/Dropping-support-for-Accelerate

Given that, I'm now leaning strongly in favor of switching to OpenBLAS.

**Comment by apjanke** [comment]
Mike Miller supports just switching to OpenBLAS, given all this: https://savannah.gnu.org/bugs/?57110#comment9

**Comment by schoeps** [comment]
> Hey, wait a minute: I just realized that the current core Homebrew `octave` is already using OpenBLAS instead of Apple Accelerate. So switching over would make us more uniform with just about everybody else.

Finally, good news indeed. This was one of the most things that annoyed me most after they closed down homebrew-science. I was complaining a lot about it at that time and eventually stopped contributing. Better late than never.

**Comment by apjanke** [comment]
Switching this to High priority, since it's probably a fix for some of the package test failures, and I think it's a logical next step to take.

**Comment by apjanke** [comment]
Done in https://github.com/octave-app/homebrew-octave-app/commit/fac77ed64c490a1024669efa5371cb265dca22eb. Will go out in the next release.
