### ISSUE TITLE
netpbm install fails: SSL error: issuer is not trusted

### ISSUE THREAD

**Issue by apjanke** [octave-app/octave-app#121]
Crap. The `netpbm` installation is failing at the download stage on OS X 10.11 El Capitan only.

It's failing due to an SSL error because the "issue is not trusted". This error does not happen on macOS 10.13 when doing a `brew install -s netpbm`. I suspect this means that there is a root certificates update that newer macOSes have received, but was not issued for OS X 10.11 because it's out of support.

```
[~] $ brew install netpbm
==> Cloning https://svn.code.sf.net/p/netpbm/code/stable
==> Checking out 3546
svn: E170013: Unable to connect to a repository at URL 'https://svn.code.sf.net/p/netpbm/code/stable'
svn: E230001: Server SSL certificate verification failed: issuer is not trusted
Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "netpbm"
Failure while executing; `svn checkout https://svn.code.sf.net/p/netpbm/code/stable /Users/janke/Library/Caches/Homebrew/netpbm--svn -r 3546` exited with 1. Here's the output:
svn: E170013: Unable to connect to a repository at URL 'https://svn.code.sf.net/p/netpbm/code/stable'
svn: E230001: Server SSL certificate verification failed: issuer is not trusted


```

Blocks https://github.com/octave-app/octave-app-bundler/issues/71. This could be a serious blocker for us continuing to support El Capitan.

**Comment by Duiesel** [comment]
> It's a system `svn` vs brewed `svn` thing. Installing svn with `brew install svn` before doing `brew install netpbm` fixes it.
> 
> May need to special-case this installation ordering in `bundle_octave`.

There are much easiest way:
`svn list https://svn.code.sf.net/p/netpbm/code/stable`
You got 
`Error validating server certificate for 'https://svn.code.sf.net:443':
 - The certificate is not issued by a trusted authority. Use the
   fingerprint to validate the certificate manually!`
Pressing `p` and "enter" will add fingerprint to that server so you just need to 
start installation again and everything gonna be ok.

**Comment by apjanke** [comment]
Doesn't that do a manually-authorized modification to the enclosing/"host" system's security setup? I'd rather not require that here; I'd like the `bundle_octave` installer to be a zero-interaction operation that works with no special host-machine setup.
