### ISSUE TITLE
Modulo does not work in parentheses

### ISSUE THREAD

**Issue by towny802** [octave-app/octave-app#14]
I just upgraded to the latest octave, and ran the code in the screenshot below. This causes a freeze which resolves to "octave exited with signal 6" in my CLI. I'm on Linux Mint, this is also apparent on Windows. This is a bug... yes?

Edit: There was a similar problem when I tried a 'try' exception handling statement.

![octave-modulo](https://user-images.githubusercontent.com/12254640/50568587-0e364e80-0d22-11e9-83bb-3ae2d3e3509e.png)

**Comment by towny802** [comment]
[log.txt](https://github.com/octave-app/octave-app/files/2719004/log.txt)

The full log, if it helps at all

**Comment by apjanke** [comment]
This repo is just for the Mac Octave.app package, not Octave itself. Please report this bug upstream to the [help-octave mailing list](https://lists.gnu.org/mailman/listinfo/help-octave).

**Comment by Andy1978** [comment]
"%" ist the start of a comment and not the modulo operator as in C. So you just have a syntax error in your code.

@apjanke Can you please point them to the bugtracker (https://savannah.gnu.org/bugs/?group=octave) rather than the mailinglist if the user thinks they have found a bug? Thank you

**Comment by apjanke** [comment]
> Can you please point them to the bugtracker (https://savannah.gnu.org/bugs/?group=octave) rather than the mailinglist if the user thinks they have found a bug?

Sure. Will do so from now on.
