### ISSUE TITLE
Qt 5.12 is not compatible with macOS 10.11

### ISSUE THREAD

**Issue by apjanke** [octave-app/octave-app#176]
Qt 5.12 requires macOS 10.12 or later. Sigh.

```
Sorry, "rcc" can not be run on this version of macOS. Qt requires macOS 10.12.0 or later, you have macOS 10.11.6.
make[3]: *** [.rcc/qrc_mimetypes.cpp] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [sub-corelib-make_first] Error 2
make[1]: *** [sub-src-make_first] Error 2
make: *** [module-qtbase-make_first] Error 2
```

Blocks #120.

Looks like if we want to use a LTS Qt release, we'll need to bump our macOS version requirement up to 10.12. Or downgrade to Qt 5.9, which is now close to EOL (May 2020), and has shown some build problems last time I tried working with it.

**Comment by apjanke** [comment]
@schoeps What do you think here for 4.4.1 updates? Should we bump to Qt 5.12 and require macOS 10.12 or later? Or downgrade to Qt 5.9, even though it's close to EOL?

**Comment by apjanke** [comment]
And, once again, I can't get a stable macOS 10.12 build box going. In vmWare Fusion, if I create a 10.12 machine and run software update on it, it starts crashing on reboot. Maybe I'll try Parallels and VirtualBox.

**Comment by schoeps** [comment]
I would go for >10.12 or even 10.13 if necessary. I think Mac users tend to be early adopters. By the way, if we offer command-line builds we could even remove qt from Octave (but then we may rely on gnuplot...).

**Comment by apjanke** [comment]
Oh, for Pete's fucking sake: my last working macOS 10.12 VM (on one of my Mac Mini build boxes) just gave up the ghost and stopped booting.

Yep, looks like we're going with 10.13 unless someone can tell me how to keep a 10.12 VM working, or wants to buy me a dedicated Octave.app build box.

**Comment by apjanke** [comment]
Closing this as a moot point/wontfix: since I can't get a pre-10.13 build box working and stable, looks like we're going to have to go macOS 10.13 regardless.
