### ISSUE TITLE
io package needs 3rd-party JARs

### ISSUE THREAD

**Issue by apjanke** [octave-app/octave-app#181]
The Octave Forge io package depends on 3rd-party Java libraries, whose JARs need to be made available on the Octave `javaclasspath` for it to run. There doesn't seem to be a standard mechanism provided by the package for dropping these in. If we ship io, we should include these JARs so users don't have to install them themselves.

##  What I had to do to get it working

* Download Xerces
  * Got Xerces2; not sure this is right
* Download ODFDOM jars from ODFToolkit
  * Had to go through the Apache archive; download link is initially broken
* Download POI
* Download commons-collections and commons-compress
  * These requirements aren't listed in the Wiki, but I found them by looking into the __POI_chk_sprt__.m file
* Download XMLBeans
  * Wiki instruction is pointing at wrong place.
* Download DOM4J
  * You have to know to pick the dom4j-2.0.x one, because 2.1.1 requires Java 8+
* Download JExcelAPI
* Download OpenXLS
* Stick all their JARs somewhere
  * Total of 19 JARs if you do all the interfaces
* Get them on the classpath using M-code instructions when you want to load the io package

I didn't even do the UNO interface; that looks like it requires dynamically crawling through an OOo installation, or grabbing the JARs from one particular version

##  TODO

* [ ] Find out how the Windows Octave installer ships these JARs.
* [ ] Find out how the MacPorts octave-io package ships these JARs.

**Comment by mmuetzel** [comment]
AFAICT, the Windows installer doesn't ship these files. It's up to the user to get them from "somewhere".

**Comment by apjanke** [comment]
Cool, thanks.

Maybe we need to ask the io package developers themselves what the recommended installation/bundling method is.

**Comment by apjanke** [comment]
Yeah. Closing this as wontfix. I think supplying the JARs for Octave Forge packages is probably out of scope for Octave.app, especially since AFAIK there's no mechanism in core Octave and its `pkg` to ship JARs like that. I think this is a problem for Forge or `io`, or maybe `pkg`, to decide how to deal with. I've been pulling in native packages that are deps for Forge packages, because there are build problems for oct/mex files when mixing system-Homebrew-managed and octapp-Homebrew-managed versions of those with the oct/mex build toolchain that's bundled with Octave.app, but I don't think Java JARs have the same problem, so probably not a good use of Octave.app effort to try to handle that, and maybe hubris to think that I'm the one to come up with the way to do that.

Closing as wontfix.
