### ISSUE TITLE
5.2.0 beta 1 still has 5.1.0 in symlink to binary

### ISSUE THREAD

**Issue by rdzman** [octave-app/octave-app#189]
## Description

I generally put a symlink in `/usr/local/bin` that points to the binary so I can launch it from the command-line. In 5.2.0 beta 1, I noticed that the link to the binary in ...

`/Applications/Octave-5.2.0.app/Contents/Resources/usr/bin`

is still named ...

`octave-octave-app\@5.1.0`

Everything seems to work fine, but thought you might want to update this.

**Comment by apjanke** [comment]
Oops!

Fixed in https://github.com/octave-app/homebrew-octave-app/commit/cca648dc71e1fff7d5c6c501ad798d746b2a0bf0. I'll roll a beta 2 release with this fix later this afternoon.

Thanks for catching this!

**Comment by apjanke** [comment]
New beta's not coming out until over the weekend; found a couple more things that need to go in the build. Please be patient.

**Comment by apjanke** [comment]
Closing this since the underlying problem is fixed. The 5.2.0 betas might be moot; Octave 6.1.0 is coming out soon.
