### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by MichelJanssens** [octave-app/octave-app#191]
## Description

I opened the download Octave-4.4.1-u1.dmg.
According to the instructions, a dialog should pop up where I could choose "Run"
Instead a virtual disk is mounted showing that I should copy the app to applications. Unfortunately, there is no App to copy. The most similar thing I could find is on the desktop. This App however simply mounts this disk again.
## Environment and Diagnostics

Please run `system env` in Octave.app, and copy & paste the output here:

```
I could not even install so there is no output to copy here.
```

**Comment by apjanke** [comment]
Does a new Finder window open up for the virtual disk? That virtual disk will contain icons for the Octave.app application and the Applications folder. That's where you do the drag & drop.

Once you've done that drag & drop, Octave.app will be in the /Applications folder. That's where you do the right-click and "Run".

**Comment by apjanke** [comment]
Closing due to lack of response. Please re-open if this is still an issue.
