### ISSUE TITLE
Trying to install the dependencies in my mac

### ISSUE THREAD

**Issue by PRUBHTEJ** [octave-app/octave-app#197]
When I'm running the command : "../configure" in my terminal, I've been
getting these errors constantly :
1. checking syntax of bison api.prefix (or name-prefix) declaration...

configure: WARNING:

I wasn't able to find a suitable style for declaring the api prefix

in a bison input file so I'm disabling bison.  We expect bison to

understand the '%define api.prefix { PREFIX }' syntax.

configure: WARNING:

I didn't find bison, or the version of bison that I found does not

support all the features that are required, but it's only a problem

if you need to reconstruct parse.cc, which is the case if you're

building from VCS sources.

checking for makeinfo... makeinfo

checking for makeinfo support for @sortas command... no

configure: WARNING:

I wasn't able to find a version of GNU makeinfo that supports the

@sortas command, but it's only a problem if you need to build the

manual, which is the case if you're building from VCS sources.

2.configure: WARNING: I need GNU Readline 4.2 or later

I did try to remove the 2nd error by using : "brew reinstall readline", but
nothing happened and I keep getting the same error.

**Comment by apjanke** [comment]
Since Homebrew's Bison installation doesn't override the macOS system-provided Bison (which is too old), you need to explicitly pull it in before doing the `configure`:

```
$ brew_opt="$(brew --prefix)/opt"
$ export YACC=$brew_opt/bison/bin/yacc
```

Are you using the configure_octave.sh script from [my octave-build repo](https://github.com/apjanke/octave-build)? That should take care of this for you.

**Comment by PRUBHTEJ** [comment]
Greetings
Yes, I am using the configure_octave.sh script from your  octave-build repo. But when I run the statement :". .. configure_octave.sh" I get the following warnings:
configure: WARNING: --without-fltk specified.  FLTK widgets will be disabled.

configure: WARNING: building documentation disabled; make dist will fail.

configure: 

configure: NOTE: Libraries or auxiliary programs may be skipped if they are not found

configure: NOTE: OR if they are missing required features on your system.



kindly guide me how to remove these warnings.

**Comment by apjanke** [comment]
Aha. I had docs turned off in the `configure_octave.sh` script, because they used to cause a build failure. I've enabled them. Do a `git pull` in `octave-BUILD` to pick up the change.

You can just ignore that FLTK warning. FLTK use is not common any more.

**Comment by PRUBHTEJ** [comment]
When I run the command : "brew install --only-dependencies octave-head" in my terminal , the following errors occur.

brew install --only-dependencies octave-head
Updating Homebrew...
Error: No available formula with the name "octave-head" 
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.

**Comment by apjanke** [comment]
That should be "octave-default", not "octave-head". Sorry about the mistake. I've fixed it in the README.

**Comment by PRUBHTEJ** [comment]
On running :"./bootstrap"
I received the following errors:
running: glibtoolize --install --copy
glibtoolize:   error: 'build-aux/config.guess' is newer: use '--force' to overwrite
glibtoolize:   error: 'build-aux/config.sub' is newer: use '--force' to overwrite
glibtoolize:   error: 'build-aux/install-sh' is newer: use '--force' to overwrite

configure: WARNING: 

I didn't find bison, or the version of bison that I found does not
support all the features that are required, but it's only a problem
if you need to reconstruct parse.cc, which is the case if you're
building from VCS sources.



My main aim is to retrieve the documentation for octave to my machine .

**Comment by apjanke** [comment]
> glibtoolize: error: 'build-aux/config.guess' is newer: use '--force' to overwrite
> glibtoolize: error: 'build-aux/config.sub' is newer: use '--force' to overwrite
> glibtoolize: error: 'build-aux/install-sh' is newer: use '--force' to overwrite

You can ignore these. This always happens and has no effect as far as I can tell. This is something that should eventually be cleaned up in the Octave build code.

> configure: WARNING:
>
> I didn't find bison, or the version of bison that I found does not
> support all the features that are required, but it's only a problem
> if you need to reconstruct parse.cc, which is the case if you're
> building from VCS sources.

The configure_octave.sh from octave-BUILD should take care of this by setting `YACC=...` before calling configure itself. Is this being emitted by configure_octave.sh? Or are you calling `./configure` directly?

**Comment by PRUBHTEJ** [comment]
I'm calling ./configure directly

**Comment by PRUBHTEJ** [comment]
![Screenshot 2020-05-07 at 7 10 35 PM](https://user-images.githubusercontent.com/47414674/81301337-91924d80-9096-11ea-9a3f-f3712f3c4a8d.png)
Is this the documentation?

**Comment by apjanke** [comment]
Submitted that FLTK warning upstream: https://savannah.gnu.org/bugs/index.php?58321

Submitted the glibtoolize errors upstream: https://savannah.gnu.org/bugs/index.php?58322

**Comment by apjanke** [comment]
> Is this the documentation?

Sure looks like it!

**Comment by PRUBHTEJ** [comment]
Finally got the documentation. 
Thank god!!!
Can u please guide how to 
1.Edit the documentation
2.Create a pull request for the changes in documentation.

**Comment by apjanke** [comment]
> Can u please guide how to
> 1.Edit the documentation
> 2.Create a pull request for the changes in documentation.

Sorry, that's beyond the scope of what I do. Please contact the Octave Maintainers or your GSoD person for that.

**Comment by PRUBHTEJ** [comment]
So as to get the documentation I used the command : "Make doxyhtml"
I encountered a few statements such as : File not found and then the names of the files .
Is it a thing to get worried about?

**Comment by PRUBHTEJ** [comment]
> > Can u please guide how to
> > 1.Edit the documentation
> > 2.Create a pull request for the changes in documentation.
> 
> Sorry, that's beyond the scope of what I do. Please contact the Octave Maintainers or your GSoD person for that.

Thank you so much regarding the clarification

**Comment by PRUBHTEJ** [comment]
> So as to get the documentation I used the command : "Make doxyhtml"
> I encountered a few statements such as : File not found and then the names of the files .
> Is it a thing to get worried about?

As far as I have accessed the documentation it is working almost fine . Kindly give me some guidance regarding this, that why i had some statements while the doxyhtml was executing in the terminal.
