### ISSUE TITLE
Improve robustness of path check

### ISSUE THREAD

**Issue by davidschlachter** [octave-app/octave-app#199]
Octave checks that it is running from `/Applications` using the following logic:

````
if not (POSIX path of (path to me) contains "/Applications/Octave-5.2.0.app") then
````

However, a user can run Octave from their home directory's local Applications folder (`~/Applications`, in my case `/Users/david/Applications`), or from any other folder named "Applications", and this check will succeed.

Octave will then fail when attempting to run binaries from the expected path:

<img width="420" alt="Screen Shot 2020-06-02 at 1 35 13 PM" src="https://user-images.githubusercontent.com/8271268/83552050-2aba5580-a4d7-11ea-9e39-0bfc0c051d7e.png">

In this case, the reason for the failure is not immediately clear to the user.

If the logic is changed to verify that the path **starts with** `/Applications`, then path verification will be more robust:

````
if not (POSIX path of (path to me) starts with "/Applications/Octave-5.2.0.app") then
````

**Comment by apjanke** [comment]
> However, a user can run Octave from their home directory's local Applications folder (~/Applications, in my case /Users/david/Applications), or from any other folder named "Applications", and this check will succeed.

This is true for Mac apps in general, but not for Octave.app. Due to how a bunch of Octave.app's dependencies are built, Octave.app can _only_ run from `/Applications`. (This is a bummer, but it is decidedly nontrivial to fix.) See #52.

This should be a better error message, though. It should say "Sorry, Octave.app can only run from /Applications. Please move this app to /Applications."

**Comment by apjanke** [comment]
Oh, wait: I completely misread what you were saying about the strictness of the path check. Yes, you're completely correct here.

Want to put in a PR so you get author credit on this one?

**Comment by davidschlachter** [comment]
Sounds good, I'm building Octave now to test that the fix works as intended and will submit a PR after.

**Comment by apjanke** [comment]
Great! Or if you're short on time, just submit the PR. This is a simple enough change, and we build & test on our side for all PRs anyway.

**Comment by davidschlachter** [comment]
Fixed in https://github.com/octave-app/octave-app-bundler/pull/98

**Comment by apjanke** [comment]
Thank you!
