### ISSUE TITLE
I can't run Octave

### ISSUE THREAD

**Issue by santiagomajo** [octave-app/octave-app#2]
When I open Octave, it appears a message:
"Font cache not found, so first plotting will be slow. Create font cache now?"
If I answer "No", it dissapears and nothing happens.
If I answer "Yes", it appears a new message:
"dyld: lazy symbol binding failed: Symbol not found: _mkostemp
  Referenced from: /Applications/Octave-4.4.0.app/Contents/Resources/usr/Cellar/fontconfig_2.13.0/2.13.0/lib/libfontconfig.1.dylib (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _mkostemp
  Referenced from: /Applications/Octave-4.4.0.app/Contents/Resources/usr/Cellar/fontconfig_2.13.0/2.13.0/lib/libfontconfig.1.dylib (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libSystem.B.dylib"
When I answer "Accept" it dissapears and nothing happens.
And when I answer "Edit", it tooks me to a rare and long script and I don't understand what to do. Can you help me with this issue? I don't know how to make Octave run.

**Comment by schoeps** [comment]
Please try to run `/Applications/Octave-4.4.0.app/Contents/Resources/usr/bin/fc-cache -frv`. Does it work?

**Comment by schoeps** [comment]
@apjanke what do you think? I'd say it's again an architecture issue. Have you already compiled on the new mac mini?

**Comment by apjanke** [comment]
This sounds like an architecture and OS version issue.

> Referenced from: /Applications/Octave-4.4.0.app/Contents/Resources/usr/Cellar/fontconfig_2.13.0/2.13.0/lib/libfontconfig.1.dylib (which was built for Mac OS X 10.13)

The most recent beta release was built on 10.11, not 10.13, and our non-beta releases will be as well.

Did you download the most recent "beta 6" release from the [Releases page](https://github.com/octave-app/octave-app/releases)? That build should fix this problem, at least as it appeared on macOS 10.11 and 10.12. I haven't tested on Mojave beta yet.

I'm on the road this weekend, but will be able to do testing when I'm back next week.

**Comment by mpiqueca** [comment]
I’m not near my Mac Mini (2011; High Sierra) just my Mac Book Pro this weekend, so the only clue I can offer is that beta 4 worked on both, but beta 6 (rc1) does not.
I have built Octave 4.4.1 through Mac Ports and it works, if that’s another clue. The 4.4.0 failed to build on Mac Ports because of a library version skew fixed upstream of Mac Ports in 4.4.1

Michael Pique
mpique@icloud.com
+1.858.354.4391 mobile

**Comment by mpiqueca** [comment]
> Did you download the most recent "beta 6" release from the Releases page? That build should fix this problem, at least as it appeared on macOS 10.11 and 10.12. I haven't tested on Mojave beta yet.
> 

I just re-downloaded rc1, beta6, and beta7 from the github and rc1 from Octave-app.org/downloads

Cksum of beta7.dmg and  both rc1.dmg are the same: 658077358 458077164

Cksum of beta6 is different : 2238540579 458076361



Installing each of them gives same result, inability to start on Mojave beta (can’t try right now on High Sierra).



Please all of you take a break and enjoy your holiday!!

Michael Pique

mpique@icloud.com
+1.858.354.4391 mobile

**Comment by apjanke** [comment]
Pretty sure OP's problem here is fixed in the newer builds (which are now building on 10.11), and @mpiqueca's issue is actually #3. Closing this out.
