### ISSUE TITLE
Suggestion to avoid problems of installing packages

### ISSUE THREAD

**Issue by elmusrati** [octave-app/octave-app#200]
## Description

Hello,
octave-app has been a great improvement in the Octave installation on MAC for a wide spectrum of end-users. However, in my case, I face always problems when installing packages. I wonder if you can include all packages (or at least the major ones like Signal, Control, etc) in octave-app. Therefore, if I need any package, I just load it (instead of installing it).   Thank you

**Comment by apjanke** [comment]
Already being looked in to! https://github.com/octave-app/octave-app/issues/109. Please subscribe to that issue for updates.

If you're having trouble with a specific package, let us know and we'll try to fix that up, too. There are existing bugs for many packages that have installation problems (unfortunately); please check for existing issues, too.

Closing as duplicate.
