### ISSUE TITLE
Octave from Octave-5.2.0-beta2.dmg does not run on Mac OS 10.9

### ISSUE THREAD

**Issue by bnzf** [octave-app/octave-app#201]
I installed Octave from Octave-5.2.0-beta2.dmg on a Mac running on OS 10.9.5. 
Installation was without problem, verification at first startup also. 
But the app quits imedately after startup ... without any notification.

I looked in info.plist which says minimum system version is 10.6.  However the app was built against Qt 5.14.2, which needs at  least OS 10.13 which is probably the reason for the "problem".

**Comment by horca17** [comment]
I installed Octave from Octave-5.2.0-beta2.dmg on a Mac running on OS 10.15.6. 
Installation was complex, I have to downgrade Sympy to v1.5.1, and have a lot of issues regarding path, gnuplot_qt, fonts, and trying to exit from octave-gui.
But what I was not able to make it start fast, so I have to wait several minutes until it become responsive, and also plotting y very painful and slow. 
And quitting and/or freezing occurs all the time too, as it happen to you.
Anybody with some responses?

**Comment by apjanke** [comment]
Eek!

> Installation was complex, I have to downgrade Sympy to v1.5.1, and have a lot of issues regarding path, gnuplot_qt, fonts, and trying to exit from octave-gui.

This is not how it's supposed to work at all: Octave.app is supposed to come with "everything included" so you shouldn't have to install, upgrade, or downgrade any other apps or libraries. Sounds like we need to include Python and Sympy in the Octave.app distribution, so it doesn't rely on external system- or /usr/local/-installed ones

> But what I was not able to make it start fast, so I have to wait several minutes until it become responsive, and also plotting is very painful and slow.
> And quitting and/or freezing occurs all the time too, as it happen to you.

Sorry, this is expected. As far as I can tell, the Octave 5.x GUI is just broken on Mac, and this is not specific to Octave.app.

We recommend just installing and using the Octave.app 4.4.1 version for now, until we can get this GUI breakage sorted out.

**Comment by horca17** [comment]
done, downgrade to 4.4.1 and works much better, sympy v1.5.1, image v2.4.1, thanks.

**Comment by bnzf** [comment]
For OS 10.9.5 Octave 4.4.1 has the same issue as v5.2. 
If Octave is not intended to run on some old systems I would suggest to put the right Minimum System Version in info.plist, so that a error message is produced.
This would help the user in avoiding to search for errors in his setup.

Attached crash report for 4.4.1:
[octave-4.4.1_2020-08-18-093000_YBookII-2.crash.zip](https://github.com/octave-app/octave-app/files/5088932/octave-4.4.1_2020-08-18-093000_YBookII-2.crash.zip)

**Comment by apjanke** [comment]
> If Octave is not intended to run on some old systems I would suggest to put the right Minimum System Version in info.plist, so that a error message is produced.

Good idea. I don't actually know how to do this, but I'll do some research.

Leaving this bug open until I can do this.

**Comment by apjanke** [comment]
Sorry for the slow action on this; very busy at the day job. Probably gonna be a week or two before I can get to this...

**Comment by apjanke** [comment]
Fixed in https://github.com/octave-app/octave-app-bundler/commit/f770b788840e54268bdcd20f22e7fc8959d5a30d

The next Octave.app build will have the Minimum OS Version set correctly.
