### ISSUE TITLE
octave-gui process not responding after mouse click inside command window

### ISSUE THREAD

**Issue by markovicpp** [octave-app/octave-app#202]
## Description

I installed fresh Octave 5.2.0 beta 2 on macOS 10.14.6 (Mojave) on 2 separate machines and was able to reproduce it on both.

Steps to reproduce:
1. Open Octave-5.2.0.app
2. Mouse click inside Command Window

Expected:
Octave does not hang

Actual:
Octave hangs, octave-gui process is not responding. Need to force quit app.

## Environment and Diagnostics

Please run `system env` in Octave.app, and copy & paste the output here:

```
SHELL=/bin/bash
TERM=xterm
TMPDIR=/var/folders/tq/rnqlh7zw8xj9h40059_tnlcr0000gn/T/
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.GPE8qmhcwj/Render
LC_NUMERIC=C
USER=username
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.ZA1zNn9aD3/Listeners
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
COLUMNS=103
PATH=/Applications/Octave-5.2.0.app/Contents/Resources/usr/bin/:/Applications/Octave-5.2.0.app/Contents/Resources/usr/bin/:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Applications/Octave-5.2.0.app/Contents/Resources/usr/Cellar/octave-octave-app@5.2.0/5.2.0/libexec/octave/5.2.0/site/exec/x86_64-apple-darwin17.7.0:/Applications/Octave-5.2.0.app/Contents/Resources/usr/Cellar/octave-octave-app@5.2.0/5.2.0/libexec/octave/api-v53/site/exec/x86_64-apple-darwin17.7.0:/Applications/Octave-5.2.0.app/Contents/Resources/usr/Cellar/octave-octave-app@5.2.0/5.2.0/libexec/octave/site/exec/x86_64-apple-darwin17.7.0:/Applications/Octave-5.2.0.app/Contents/Resources/usr/Cellar/octave-octave-app@5.2.0/5.2.0/libexec/octave/5.2.0/exec/x86_64-apple-darwin17.7.0:/Applications/Octave-5.2.0.app/Contents/Resources/usr/Cellar/octave-octave-app@5.2.0/5.2.0/bin
_=/usr/bin/env
PWD=/Users/username
GS_OPTIONS=-sICCProfilesDir=/Applications/Octave-5.2.0.app/Contents/Resources/usr/opt/ghostscript/share/ghostscript/9.52/iccprofiles/ -sGenericResourceDir=/Applications/Octave-5.2.0.app/Contents/Resources/usr/opt/ghostscript/share/ghostscript/9.52/Resource/ -sFontResourceDir=/Applications/Octave-5.2.0.app/Contents/Resources/usr/opt/ghostscript/share/ghostscript/9.52/Resource/Font
LANG=en_SK.UTF-8
XPC_FLAGS=0x0
F77=/Applications/Octave-5.2.0.app/Contents/Resources/usr/bin/gfortran
LINES=47
XPC_SERVICE_NAME=0
HOME=/Users/username
SHLVL=2
FC=/Applications/Octave-5.2.0.app/Contents/Resources/usr/bin/gfortran
GNUTERM=qt
LOGNAME=username
LC_TIME=C
ans = 0
>>
```

If your problem is weird, please also run `octave_app_diagnostic_dump` in Octave.app and attach its output file to this issue.

If your problem is Octave.app freezing with a spinning “beachball” mouse cursor, if you can, please take a spindump, zip it, and attach it to this issue. (To create a spindump, open Activity Monitor while Octave.app is frozen, select the `octave-gui` process, click the “gear” button in the upper left, and choose "Spindump".)

[Sample of octave-gui.txt.zip](https://github.com/octave-app/octave-app/files/5170808/Sample.of.octave-gui.txt.zip)

**Comment by apjanke** [comment]
This looks like the same "freeziness" issue we're seeing in https://github.com/octave-app/octave-app/issues/120 with all the 5.x builds. (And is why we haven't actually made a non-beta 5.x release yet.)

I'm afraid I don't know what's causing it or how to fix it yet.

There's some hope on the way, though: running `octave --gui` directly from the command line seems to work. And the release candidate for 6.0.90 doesn't seem to have the freeziness issue so far.

**Comment by apjanke** [comment]
I've made a central bug to track all the "GUI freeziness in 5.x" issues: https://github.com/octave-app/octave-app/issues/208.

Closing this as a dupe. Please follow that other bug if you'd like progress updates.
