### ISSUE TITLE
Failed to install image package on Octave.app on MacosX Catalina 

### ISSUE THREAD

**Issue by bwhch** [octave-app/octave-app#203]
## Description

I tried both pkg install -forge image and pkg install image-2.12.0.tar.gz using both Octave GUI 4.4.1 and 5.2.0. to no avail. Attached is the error message I received. Would appreciate any help. Many thanks!
<img width="675" alt="Screenshot 2020-09-04 at 5 40 22 PM" src="https://user-images.githubusercontent.com/70751730/92226826-e83e5580-eed7-11ea-847a-386d0d644775.png">

 

## Environment and Diagnostics

Please run `system env` in Octave.app, and copy & paste the output here:

```
[output goes here]
```

If your problem is weird, please also run `octave_app_diagnostic_dump` in Octave.app and attach its output file to this issue.

If your problem is Octave.app freezing with a spinning “beachball” mouse cursor, if you can, please take a spindump, zip it, and attach it to this issue. (To create a spindump, open Activity Monitor while Octave.app is frozen, select the `octave-gui` process, click the “gear” button in the upper left, and choose "Spindump".)

**Comment by apjanke** [comment]
Sorry you're having trouble!

I can't tell from the error message you posted what's going on: those just look like warnings from Perl about your locale setup; sounds like it doesn't like the Singaporean `en_SG`.

Could you include the complete output from your attempt to do `pkg install -forge image`, so we can see what the actual build error was, and if there were any other warnings issued? Copy and paste it as plain text instead of a screen shot; that'll let you include more text, and will make it searchable.

**Comment by apjanke** [comment]
Well now that's weird. When I just install fontconfig via Homebrew on the same 10.15 machine and run `fc-cache` from there, I still get the "/Library/Fonts: Unable to revert mtime: /Library/Fonts" message, but it succeeds:

```
janke@catawba ~ % sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.6
BuildVersion:	19G2021
janke@catawba ~ % fc-cache --version
fontconfig version 2.13.1
janke@catawba ~ % fc-cache -frv
/usr/share/fonts: skipping, no such directory
/System/Library/Fonts: caching, new cache contents: 523 fonts, 1 dirs
/System/Library/Fonts/Supplemental: caching, new cache contents: 440 fonts, 0 dirs
/Library/Fonts: Unable to revert mtime: /Library/Fonts
caching, new cache contents: 1 fonts, 0 dirs
/Users/janke/Library/Fonts: caching, new cache contents: 0 fonts, 0 dirs
/System/Library/AssetsV2/com_apple_MobileAsset_Font6: caching, new cache contents: 0 fonts, 0 dirs
/Users/janke/.local/share/fonts: skipping, no such directory
/Users/janke/.fonts: skipping, no such directory
/System/Library/Fonts/Supplemental: skipping, looped directory detected
/usr/local/var/cache/fontconfig: cleaning cache directory
/usr/local/var/cache/fontconfig: invalid cache file: 14bbaa569fa80b3226d8be152e7657ad-le64.cache-7
/Users/janke/.cache/fontconfig: not cleaning non-existent cache directory
/Users/janke/.fontconfig: not cleaning non-existent cache directory
fc-cache: succeeded
janke@catawba ~ % echo $?
0
janke@catawba ~ % fc-cache --version
fontconfig version 2.13.1
janke@catawba ~ % which fc-cache
/usr/local/bin/fc-cache
janke@catawba ~ % 
```

Here's the Octave.app run for comparison:

```
janke@catawba ~ % /Applications/Octave-6.0.90.app/Contents/Resources/usr/bin/fc-cache --version
fontconfig version 2.13.1
janke@catawba ~ % /Applications/Octave-6.0.90.app/Contents/Resources/usr/bin/fc-cache -frv     
/usr/share/fonts: skipping, no such directory
/System/Library/Fonts: caching, new cache contents: 523 fonts, 1 dirs
/System/Library/Fonts/Supplemental: caching, new cache contents: 440 fonts, 0 dirs
/Library/Fonts: Unable to revert mtime: /Library/Fonts
caching, new cache contents: 1 fonts, 0 dirs
/Users/janke/Library/Fonts: caching, new cache contents: 0 fonts, 0 dirs
/Users/janke/Library/Fonts: failed to write cache
/System/Library/Assets/com_apple_MobileAsset_Font5: skipping, no such directory
/Users/janke/.local/share/fonts: skipping, no such directory
/Users/janke/.fonts: skipping, no such directory
/System/Library/Fonts/Supplemental: skipping, looped directory detected
/Users/janke/.cache/fontconfig: cleaning cache directory
/Users/janke/.fontconfig: not cleaning non-existent cache directory
/Applications/Octave-6.0.90.app/Contents/Resources/usr/bin/fc-cache: failed
janke@catawba ~ % 
```

Looks to me like the only difference between the two is the "succeeded" or "failed" line at the end, and the exit status.

But... the `~/.cache/fontconfig` directory doesn't appear.

```
janke@catawba ~ % fc-cache -frv | tail -2
Unable to revert mtime: /Library/Fonts
/Users/janke/.fontconfig: not cleaning non-existent cache directory
fc-cache: succeeded
janke@catawba ~ % ls ~/.cache/fontconfig
ls: /Users/janke/.cache/fontconfig: No such file or directory
janke@catawba ~ % ls ~/.cache           
janke@catawba ~ %
```

I wonder where the cache is going, and why it's different for the two fontconfig installations? Is it an environment variable thing?

**Comment by apjanke** [comment]
Aha! The Homebrewed one is going to `/usr/local/var/cache/fontconfig`.

The `var` for the prefix for Octave.app is actually linked to the system `/var`, because app bundles are not supposed to modify their contents, especially if they are signed (which we would like to do some day). See https://github.com/octave-app/octave-app/issues/60. Maybe we're actually running in to one of those issues now.

Think I'll report this upstream to the fontconfig folks and see what they have to say.

**Comment by apjanke** [comment]
Oh, sorry; those last two comments were for a different issue. I'll delete them.

**Comment by chris-mair** [comment]
Hi,

sorry I'm late, just discovered this comunity.

I had the same problem with my en_IT locale which Perl found too exotic too...

Note that in my case this was just a *WARNING*, the package installed just fine. If you could not 
install the package there might be something else going on (e.g. you did not install the xcode command 
line tools?).

Anyway, to get rid of those warnings, I edited Octave-4.4.1.app/Contents/Resources/Scripts/main.scpt with the Apple Script editor and changed:

on export_lang()
	return "default_lang=$(osascript -e 'user locale of (get system info)'); export LANG=$default_lang.UTF-8;"
end export_lang

to 

on export_lang()
	return "default_lang=en_US; export LANG=$default_lang.UTF-8;"
end export_lang

this way hardcoding the locale.

Again, in my case this was just cosmetic, to get rid of the locale warnings...

-- Chris

**Comment by apjanke** [comment]
Thanks for the extra info, @chris-mair!

> I had the same problem with my en_IT locale which Perl found too exotic too...
>
> Note that in my case this was just a WARNING, the package installed just fine.

Hmmm. en_IT doesn't sound exotic to me. I wonder why Perl doesn't like it? Octave.app uses the system perl and not one we ship ourselves.

Oh, shoot: here's the locales that ship with my (US) macOS 10.14:

```
ls /usr/share/locale
UTF-8             de                en_GB.ISO8859-15  fi_FI.ISO8859-1   hu_HU             ko_KR.UTF-8       pl_PL             sr_YU.ISO8859-2
af_ZA             de_AT             en_GB.US-ASCII    fi_FI.ISO8859-15  hu_HU.ISO8859-2   ko_KR.eucKR       pl_PL.ISO8859-2   sr_YU.ISO8859-5
af_ZA.ISO8859-1   de_AT.ISO8859-1   en_GB.UTF-8       fi_FI.UTF-8       hu_HU.UTF-8       la_LN.ISO8859-1   pl_PL.UTF-8       sr_YU.UTF-8
af_ZA.ISO8859-15  de_AT.ISO8859-15  en_IE             fr                hy_AM             la_LN.ISO8859-15  pt_BR             sv
af_ZA.UTF-8       de_AT.UTF-8       en_IE.UTF-8       fr_BE             hy_AM.ARMSCII-8   la_LN.ISO8859-2   pt_BR.ISO8859-1   sv_SE
am_ET             de_CH             en_NZ             fr_BE.ISO8859-1   hy_AM.UTF-8       la_LN.ISO8859-4   pt_BR.UTF-8       sv_SE.ISO8859-1
am_ET.UTF-8       de_CH.ISO8859-1   en_NZ.ISO8859-1   fr_BE.ISO8859-15  is_IS             la_LN.US-ASCII    pt_PT             sv_SE.ISO8859-15
be_BY             de_CH.ISO8859-15  en_NZ.ISO8859-15  fr_BE.UTF-8       is_IS.ISO8859-1   locale.alias      pt_PT.ISO8859-1   sv_SE.UTF-8
be_BY.CP1131      de_CH.UTF-8       en_NZ.US-ASCII    fr_CA             is_IS.ISO8859-15  lt_LT             pt_PT.ISO8859-15  tr
be_BY.CP1251      de_DE             en_NZ.UTF-8       fr_CA.ISO8859-1   is_IS.UTF-8       lt_LT.ISO8859-13  pt_PT.UTF-8       tr_TR
be_BY.ISO8859-5   de_DE.ISO8859-1   en_US             fr_CA.ISO8859-15  it_CH             lt_LT.ISO8859-4   ro                tr_TR.ISO8859-9
be_BY.UTF-8       de_DE.ISO8859-15  en_US.ISO8859-1   fr_CA.UTF-8       it_CH.ISO8859-1   lt_LT.UTF-8       ro_RO             tr_TR.UTF-8
bg_BG             de_DE.UTF-8       en_US.ISO8859-15  fr_CH             it_CH.ISO8859-15  nb                ro_RO.ISO8859-2   uk_UA
bg_BG.CP1251      el_GR             en_US.US-ASCII    fr_CH.ISO8859-1   it_CH.UTF-8       nl                ro_RO.UTF-8       uk_UA.ISO8859-5
bg_BG.UTF-8       el_GR.ISO8859-7   en_US.UTF-8       fr_CH.ISO8859-15  it_IT             nl_BE             ru                uk_UA.KOI8-U
ca_ES             el_GR.UTF-8       eo                fr_CH.UTF-8       it_IT.ISO8859-1   nl_BE.ISO8859-1   ru_RU             uk_UA.UTF-8
ca_ES.ISO8859-1   en_AU             es_ES             fr_FR             it_IT.ISO8859-15  nl_BE.ISO8859-15  ru_RU.CP1251      zh_CN
ca_ES.ISO8859-15  en_AU.ISO8859-1   es_ES.ISO8859-1   fr_FR.ISO8859-1   it_IT.UTF-8       nl_BE.UTF-8       ru_RU.CP866       zh_CN.GB18030
ca_ES.UTF-8       en_AU.ISO8859-15  es_ES.ISO8859-15  fr_FR.ISO8859-15  ja                nl_NL             ru_RU.ISO8859-5   zh_CN.GB2312
cs                en_AU.US-ASCII    es_ES.UTF-8       fr_FR.UTF-8       ja_JP             nl_NL.ISO8859-1   ru_RU.KOI8-R      zh_CN.GBK
cs_CZ             en_AU.UTF-8       et_EE             he                ja_JP.SJIS        nl_NL.ISO8859-15  ru_RU.UTF-8       zh_CN.UTF-8
cs_CZ.ISO8859-2   en_CA             et_EE.ISO8859-15  he_IL             ja_JP.UTF-8       nl_NL.UTF-8       sk_SK             zh_CN.eucCN
cs_CZ.UTF-8       en_CA.ISO8859-1   et_EE.UTF-8       he_IL.UTF-8       ja_JP.eucJP       no                sk_SK.ISO8859-2   zh_HK
da                en_CA.ISO8859-15  eu_ES             hi_IN.ISCII-DEV   kk_KZ             no_NO             sk_SK.UTF-8       zh_HK.Big5HKSCS
da_DK             en_CA.US-ASCII    eu_ES.ISO8859-1   hr                kk_KZ.PT154       no_NO.ISO8859-1   sl_SI             zh_HK.UTF-8
da_DK.ISO8859-1   en_CA.UTF-8       eu_ES.ISO8859-15  hr_HR             kk_KZ.UTF-8       no_NO.ISO8859-15  sl_SI.ISO8859-2   zh_TW
da_DK.ISO8859-15  en_GB             eu_ES.UTF-8       hr_HR.ISO8859-2   ko_KR             no_NO.UTF-8       sl_SI.UTF-8       zh_TW.Big5
da_DK.UTF-8       en_GB.ISO8859-1   fi_FI             hr_HR.UTF-8       ko_KR.CP949       pl                sr_YU             zh_TW.UTF-8
``` 

There's `it_IT` but no `en_IT`, and no `*_SG` at all.

So I think what Octave.app's startup script needs to do is check that constructed "desired" locale against the list of installed locales, and if it's not present, fall back to one that's available, maybe defaulting to `en_US.UTF-8`, which I bet is installed on every macOS installation. (Or can it fall back to just `it.UTF-8`? Does that get constructed from the `it` and `UTF-8` locale definitions somehow?)

Since the installation worked for you, @chris-mair , I think the locale warnings were a red herring for original poster, and I'm splitting the "bogus locale" problem off to a separate issue: https://github.com/octave-app/octave-app/issues/215.

@chris-mair, could you post what you get for the output of `locale` (from the macOS terminal)?

**Comment by chris-mair** [comment]
> could you post what you get for the output of locale (from the macOS terminal)?

Sure!

```
$ osascript -e 'user locale of (get system info)'
```

always gives 

```
en_IT
```

This is correct, in the sense that I'm using this Mac in region 'Italy' and language 'English'.

However, the BSD-subsystem doesn't like that. As you have found out, there is no such locale. So
with my custom .profile removed I get:

```
$ locale
LANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

I do all my dev work in en_US, so normally I keep this in my .profile:

```
export LC_ALL=en_US.UTF-8
export LC_CTYPE=UTF-8
export LANG=en_US.UTF-8
```

and with this I get:

```
$ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
```

So the perfect solution would probably be to check /usr/share/locale and fall back to en_US in case
of "strange" locale.


But, again: as far as I see this is only a cosmetic problem with perl complaining when 
you deal with packages. Not a breaking bug.

Thanks!

-- Chris.

**Comment by apjanke** [comment]
Thank you Chris! That's helpful.

I agree it's just cosmetic. (I think.) Dealing with it under the other issue.

Closing this issue about `image` failing to install due to lack of response from OP. (I cannot reproduce.)
