### ISSUE TITLE
GUI is freezey in 5.x (and maybe 6.x)

### ISSUE THREAD

**Issue by apjanke** [octave-app/octave-app#208]
Ever since Octave hit 5.0, the GUI in our Octave.app builds for 5.x has been super freezey, making it unusable. Either the GUI will hang and beachball immediately upon launch, or shortly after you start typing stuff in the Command Window for the first time. Takes a Force Kill to close it.

This is why our main production release is still 4.4.1, and we've only released betas for the 5.x releases.

This problem has been going on for a long while; I'm just now writing this up as a separate bug.

Blocks #120 
Caused #202, I think.

I have no idea what's causing it or how to fix it.

**Comment by schoeps** [comment]
I am playing with 6.0.90 for some time and it was stable until now. Maybe we are lucky?

**Comment by mpiqueca** [comment]
Agree so far.  It ran through every "rundemos()" even the graphics ones.  The largest problem I had (which has nothing to do with octave-app of course) is my code in places used "continue" to break out of a "case";  that seems to have been disallowed in 6.0.90. I'm mostly using just the command line though.

**Comment by apjanke** [comment]
> I am playing with 6.0.90 for some time and it was stable until now (macOS 10.15.6). Maybe we are lucky?!

Oh my gosh, fingers crossed.

**Comment by apjanke** [comment]
This seems all fixed now with the 6.x line. Calling this closed.
