### ISSUE TITLE
Installs on OSX 10.15.6, but fails to open

### ISSUE THREAD

**Issue by neeemo-max** [octave-app/octave-app#212]
## Description

Replace this section with a description of the problem, including:
  * Downloaded the dmg, and extracted the file, then tried to launch the application
  * I expected the Octave application to open
  * The application failed to open and OSX offered to move the application to the trash. 

I reinstalled the application, the same result.

**Comment by apjanke** [comment]
Did you move the application to the `/Applications` folder before running it? Unfortunately, that's the only place that Octave.app can run from, due to absolute paths baked in to the program.

**Comment by neeemo-max** [comment]
Moving the application to the /Applications folder, and "trusting" the developer fixed the problem. Thank you!
