### ISSUE TITLE
sound command not working

### ISSUE THREAD

**Issue by MacDragon** [octave-app/octave-app#213]
## Description

try to play any data as a sound using sound command, get error.

f1=randn(1, 1000);
sound(f1)

error: audioplayer: NBITS must be 8, 16, or 24
error: called from
    audioplayer at line 112 column 19
    sound at line 64 column 8

going in further:

>> audioplayer (f1, 8000, 8);
error: audioplayer: NBITS must be 8, 16, or 24
error: called from
    audioplayer at line 112 column 19

Otherwise it seems provisionally fairly stable.

## Environment and Diagnostics

octave 6.0.90RC1

big-sur & catalina

Please run `system env` in Octave.app, and copy & paste the output here:

>> system env
SHELL=/bin/bash
TERM=xterm
TMPDIR=/var/folders/7f/xvnq7cvs46qfqrf5wcnzhp700000gn/T/
LC_NUMERIC=C
USER=visa
COMMAND_MODE=unix2003
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.ZFXUCTSZBC/Listeners
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x2
COLUMNS=113
PATH=/Applications/Octave-6.0.90.app/Contents/Resources/usr/bin/:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Octave-6.0.90.app/Contents/Resources/usr/Cellar/octave-octave-app@6.0.90/6.0.90/libexec/octave/6.0.90/site/exec/x86_64-apple-darwin18.7.0:/Applications/Octave-6.0.90.app/Contents/Resources/usr/Cellar/octave-octave-app@6.0.90/6.0.90/libexec/octave/api-v55/site/exec/x86_64-apple-darwin18.7.0:/Applications/Octave-6.0.90.app/Contents/Resources/usr/Cellar/octave-octave-app@6.0.90/6.0.90/libexec/octave/site/exec/x86_64-apple-darwin18.7.0:/Applications/Octave-6.0.90.app/Contents/Resources/usr/Cellar/octave-octave-app@6.0.90/6.0.90/libexec/octave/6.0.90/exec/x86_64-apple-darwin18.7.0:/Applications/Octave-6.0.90.app/Contents/Resources/usr/Cellar/octave-octave-app@6.0.90/6.0.90/bin
_=/usr/bin/env
__CFBundleIdentifier=org.octave-app.Octave
PWD=/Users/xxx
GS_OPTIONS=-sICCProfilesDir=/Applications/Octave-6.0.90.app/Contents/Resources/usr/opt/ghostscript/share/ghostscript/9.52/iccprofiles/ -sGenericResourceDir=/Applications/Octave-6.0.90.app/Contents/Resources/usr/opt/ghostscript/share/ghostscript/9.52/Resource/ -sFontResourceDir=/Applications/Octave-6.0.90.app/Contents/Resources/usr/opt/ghostscript/share/ghostscript/9.52/Resource/Font
LANG=en_FI.UTF-8
XPC_FLAGS=0x0
F77=/Applications/Octave-6.0.90.app/Contents/Resources/usr/bin/gfortran
LINES=50
XPC_SERVICE_NAME=0
HOME=/Users/xxx
SHLVL=2
FC=/Applications/Octave-6.0.90.app/Contents/Resources/usr/bin/gfortran
GNUTERM=qt
LOGNAME=xxx
DISPLAY=/private/tmp/com.apple.launchd.9Cw4Qr93vQ/org.macosforge.xquartz:0
LC_TIME=C
ans = 0

If your problem is weird, please also run `octave_app_diagnostic_dump` in Octave.app and attach its output file to this issue.

If your problem is Octave.app freezing with a spinning “beachball” mouse cursor, if you can, please take a spindump, zip it, and attach it to this issue. (To create a spindump, open Activity Monitor while Octave.app is frozen, select the `octave-gui` process, click the “gear” button in the upper left, and choose "Spindump".)

**Comment by apjanke** [comment]
Works for me, under Octave.app 8.4.0 and 9.2.0 beta1, on macOS 14.5 on an iMac Intel.

My repro script:

```
function play_rando_sound

n = 30 * 1000;

f1=randn(1, n);
sound(f1)

endfunction
```

When I run `play_rando_sound`, it runs to completion without raising an error, and I hear a "pssssshshshshsh" white-noise sound coming out of my speakers.

I'm gonna guess this was an upstream problem that got fixed between now and when this issue was first posted. 6.0.90 was a pre-release in the first place.

Closing as "Fixed Upstream". If this problem still happens on newer Octave.app releases, please re-open this bug.
