### ISSUE TITLE
OpenBLAS picks MAX_THREADS=6 on a 8 core / 16 thread machine

### ISSUE THREAD

**Issue by chris-mair** [octave-app/octave-app#214]
Hi,

I'm using octave-app 4.4.1-u2-beta3 on macOS 10.14.6 on a mpb with 8 cores/16 threads.

>> version("-blas")
ans = OpenBLAS (config: OpenBLAS 0.3.9 DYNAMIC_ARCH NO_AFFINITY USE_OPENMP Haswell MAX_THREADS=6)

Note the MAX_THREADS=6 and, indeed, if I multiply a large matrix I see ~ 600% CPU usage in Activity Monitor.

I was expecting MAX_THREADS to be either 8 or 16 on this machine and to be able to use all cores.

Does anybody know where this MAX_THREADS=6 comes from? Also I thought this could be somehow
influenced by env variables like OPENBLAS_NUM_THREADS, but appearantly not. I've tried to export OPENBLAS_NUM_THREADS=8 in main.scpt where the executable is invoked, but nothing seems
to change the above MAX_THREADS=6.

Is this number (6) somehow hard-compiled into the bundled OpenBLAS?

Thanks!
Chris.

---
```
>> system env
SHELL=/bin/bash
TERM=xterm
TMPDIR=/var/folders/vv/[...]/T/
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.[...]/Render
LC_NUMERIC=C
USER=chris
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.[...]/Listeners
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
COLUMNS=117
PATH=/Applications/Octave-4.4.1.app/Contents/Resources/usr/bin/:/Applications/Octave-4.4.1.app/Contents/Resources/usr/bin/:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Applications/Octave-4.4.1.app/Contents/Resources/usr/Cellar/octave-octave-app@4.4.1/4.4.1/libexec/octave/4.4.1/site/exec/x86_64-apple-darwin17.7.0:/Applications/Octave-4.4.1.app/Contents/Resources/usr/Cellar/octave-octave-app@4.4.1/4.4.1/libexec/octave/api-v52/site/exec/x86_64-apple-darwin17.7.0:/Applications/Octave-4.4.1.app/Contents/Resources/usr/Cellar/octave-octave-app@4.4.1/4.4.1/libexec/octave/site/exec/x86_64-apple-darwin17.7.0:/Applications/Octave-4.4.1.app/Contents/Resources/usr/Cellar/octave-octave-app@4.4.1/4.4.1/libexec/octave/4.4.1/exec/x86_64-apple-darwin17.7.0:/Applications/Octave-4.4.1.app/Contents/Resources/usr/Cellar/octave-octave-app@4.4.1/4.4.1/bin
_=/usr/bin/env
PWD=/Users/chris/[...]
GS_OPTIONS=-sICCProfilesDir=/Applications/Octave-4.4.1.app/Contents/Resources/usr/opt/ghostscript/share/ghostscript/9.50/iccprofiles/ -sGenericResourceDir=/Applications/Octave-4.4.1.app/Contents/Resources/usr/opt/ghostscript/share/ghostscript/9.50/Resource/ -sFontResourceDir=/Applications/Octave-4.4.1.app/Contents/Resources/usr/opt/ghostscript/share/ghostscript/9.50/Resource/Font
LANG=en_US.UTF-8
XPC_FLAGS=0x0
F77=/Applications/Octave-4.4.1.app/Contents/Resources/usr/bin/gfortran
LINES=39
XPC_SERVICE_NAME=0
HOME=/Users/chris
SHLVL=2
FC=/Applications/Octave-4.4.1.app/Contents/Resources/usr/bin/gfortran
GNUTERM=qt
LOGNAME=chris
DISPLAY=/private/tmp/com.apple.launchd.[...]/org.macosforge.xquartz:0
LC_TIME=C
ans = 0
```

**Comment by mpiqueca** [comment]
Did you try 

export OMP_NUM_THREADS=16

If OPENBLAS is using Open MP, as your config suggests, that’s worth a try.

Sent from my iPhone.
Michael Pique mpique@icloud.com +1 858-354-4391

**Comment by chris-mair** [comment]
Hi,

> export OMP_NUM_THREADS=16

thanks! I discovered something new.

When I run:

export OMP_NUM_THREADS=1; /Applications/Octave-4.4.1.app/Contents/Resources/usr/bin/octave-octave-app-4.4.1

a matrix multiply will indeed use only 1 core as shown in Activity monitor. With 2 it will use 2 cores....

However, I cannot go past 6!

It seems as if OMP_NUM_THREADS works, but with a maximum of 6.

The output of  version("-blas") is always MAX_THREADS=6.

So effectively OMP_NUM_THREADS is cappet to MAX_THREADS = 6 for some reason.

Chris.

**Comment by apjanke** [comment]
> Is this number (6) somehow hard-compiled into the bundled OpenBLAS?

Hmmm. 6 is an unusual number for this sort of thing; usually they come in powers of 2. I think I used to run the Octave build on a VM with 6 vcores/3 hw cores, though. That sounds awfully coincidental.

This is what I see on my 10-core iMac Pro angharad with Octave.app 4.4.1, 5.1 beta, and 6.0.90 RC:

```
📙  ~ 
  /Applications/Octave-4.4.1.app/Contents/Resources/usr/bin/octave-octave-app-4.4.1 -q
octave:1> version -blas
ans = OpenBLAS (config: OpenBLAS 0.3.9 DYNAMIC_ARCH NO_AFFINITY USE_OPENMP Haswell MAX_THREADS=6)
octave:2> exit

  /Applications/Octave-5.2.0.app/Contents/Resources/usr/bin/octave-octave-app@5.1.0 -q
octave:1> version -blas
ans = OpenBLAS (config: OpenBLAS 0.3.7 DYNAMIC_ARCH NO_AFFINITY USE_OPENMP Haswell MAX_THREADS=3)
octave:2> exit

📓  ~ 
  /Applications/Octave-6.0.90.app/Contents/Resources/usr/bin/octave-octave-app@6.0.90 -q
octave:1> version -blas
ans = OpenBLAS (config: OpenBLAS 0.3.10 DYNAMIC_ARCH NO_AFFINITY USE_OPENMP Haswell MAX_THREADS=6)
octave:2> exit
```

My build VM, hicks, is currently using 14 vcores, and I think that's the configuration it was in when I built the 6.0.90 RC Octave.app.

My vanilla Homebrew-installed Octave also reports 6 max threads, too:

```
/usr/local/bin/octave -q
octave:1> version -blas
ans = OpenBLAS (config: OpenBLAS 0.3.12 DYNAMIC_ARCH NO_AFFINITY USE_OPENMP Haswell MAX_THREADS=6)
octave:2> exit
```

Though I installed it from a bottle, and I suspect that Homebrew's bottle build farm is using 3 core/6 vcore VMs.



Oho, look at this! It appears that the Homebrew openblas formula is a "relocatable" bottle, which means that the Octave.app build is using a pre-built openblas:

```
hicks:octave-app-bundler janke$ ./bundle_octave brew info openblas
Building Octave-5.2.0.app at /Applications/Octave-5.2.0.app from formula octave-octave-app@5.2.0
Re-staging existing build dir from /Applications/Octave-5.2.0.app-UNSTAGED
openblas: stable 0.3.9 (bottled), HEAD [keg-only]
Optimized BLAS library
https://www.openblas.net/
/Applications/Octave-5.2.0.app/Contents/Resources/usr/Cellar/openblas/0.3.9 (23 files, 120MB)
  Poured from bottle on 2020-04-25 at 15:01:31
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/openblas.rb
```

Which means we may be seeing a max threads limitation that is baked in by the way that Homebrew builds openblas for its bottles.

Let's do some googling and see if there's an OpenBLAS build option to raise that MAX_THREADS setting. And then let's bring this up with the Homebrew core maintainers once we've confirmed this is the issue.

In the mean time, I'm doing `brew reinstall --build-from-source openblas` on angharad to see if that gets a different MAX_THREADS value.

**Comment by apjanke** [comment]
Ayup. After I rebuilt my Homebrewed `openblas`, I ran my Homebrewed `octave`, and there's my 20 max threads:

```
octave -q
octave:1> version -blas
ans = OpenBLAS (config: OpenBLAS 0.3.12 DYNAMIC_ARCH NO_AFFINITY USE_OPENMP Haswell MAX_THREADS=20)
```

I do not know what the Right Way to fix this is, offhand. Probably something like building `openblas` with a large number of max threads (like 20 or 40), and then having the Octave.app launcher script set `$OMP_NUM_THREADS` based on the number of CPU cores detected at run time. I'll ask the Homebrew folks what they think, too.

**Comment by apjanke** [comment]
Upstream bug report: https://discourse.brew.sh/t/openblas-bottle-max-threads-is-fixed-to-6/9099

**Comment by chris-mair** [comment]
Hi Andrew,

thanks for looking into this!

According to Adrian Ho's reply in the brew forum, we could make a pull request to 
add NUM_THREADS = 64 or something like that to the openblas formula:

https://github.com/Homebrew/homebrew-core/blob/master/Formula/openblas.rb

> [...] and then having the Octave.app launcher script set $OMP_NUM_THREADS based on the number of CPU cores detected at run time

This is not even necessary, apparently. Adrian cites the FAQ:

> at runtime, it will scale down the maximum number of threads it uses to match the number of cores physically available

I've never used brew and don't know Ruby. Could you make this pull request? 
Otherwise I can try doing it... I see there are some other env variables there, I guess I could bluff my way as a Ruby dev with a one liner :) 

Thanks!
Chris.

**Comment by apjanke** [comment]
> Could you make this pull request?

Yep.

**Comment by apjanke** [comment]
Upstream PR: https://github.com/Homebrew/homebrew-core/pull/64550

**Comment by chris-mair** [comment]
Thanks @apjanke !

Out of curiosity I compiled my own OpenBLAS (via MacPorts) and substituted the .a and .dylib in Octave-4.4.1.app/Contents/Resources/usr/Cellar/openblas/0.3.9/lib

This got me from

ans = OpenBLAS (config: OpenBLAS 0.3.9 DYNAMIC_ARCH NO_AFFINITY USE_OPENMP Haswell MAX_THREADS=6)

to 

ans = OpenBLAS (config: OpenBLAS 1 NO_AFFINITY HASWELL MAX_THREADS=16)

(version is actually 0.3.12... don't mind the 1)

and this quick test:

```
t = 0; for k = 1:10; A=rand(8192, 'single'); B=rand(8192, 'single'); tic; C=A*B; t = t + toc; end; disp((2 * 8192^3 - 8192^2)/(t/10)/1E9);
```

went from 530 +- 15 GFLOPS to 640 +- 20 which is coming really close to what MATLAB does with the MKL ( 675 +- 30 ).

Nice :)

Chris.

**Comment by apjanke** [comment]
> went from 530 +- 15 GFLOPS to 640 +- 20 which is coming really close to what MATLAB does with the MKL ( 675 +- 30 ).

Good sign!

Upstream Homebrew looks inclined to accept the PR increasing NUM_THREADS in the core `openblas` build, so I'm just going to wait for that to hit production, and then I'll do a new build of the Octave.app 6 Release Candidate with it.

**Comment by apjanke** [comment]
The high-NUM_THREADS `openblas` patch has been merged upstream in core Homebrew. I'll put out a new Octave.app 6.0 Release Candidate build using it tomorrow.

**Comment by apjanke** [comment]
Aaaaand, build failure. Maybe next week, folks!

**Comment by apjanke** [comment]
This was fixed in Octave.app 6.1.0.

```
>> version -blas
ans = OpenBLAS (config: OpenBLAS 0.3.13 DYNAMIC_ARCH NO_AFFINITY USE_OPENMP Haswell MAX_THREADS=56)
>>
```
