### ISSUE TITLE
Octave 5.2 in macOS Big Sur

### ISSUE THREAD

**Issue by lfsequeira** [octave-app/octave-app#217]
## Description

Installed Octave 5.2.0 beta 2 in macOS Big Sur

Launched by control-clicking and choosing "Open".

The application appears to start, but the menus are the user interface never appear.
The "Octave-GUI" appears in the Application Switcher (command-tab) and in the Force Quit window (command-option-escape). The only thing one can do is force quit.

The application never appears as "non-responding" and it never shows the "beachball".

## Environment and Diagnostics

Please run `system env` in Octave.app, and copy & paste the output here:

[impossible since the application interface never appears]

**Comment by apjanke** [comment]
Can you try the new Octave.app 6.0.90 release candidate? https://github.com/octave-app/octave-app/releases/tag/v6.0.90-rc1

**Comment by lfsequeira** [comment]
Thank you!

The new version appears to be working fine.

LS

**Comment by apjanke** [comment]
Cool. Going to close this then: due to various issues with Octave 5.x on Mac, we're going to skip 5.x entirely and go right to Octave 6.
