### ISSUE TITLE
Mac OS X system crash on launching Octave 4.4.1 or 4.4.0 or 6 RC1

### ISSUE THREAD

**Issue by DouglasStrachan** [octave-app/octave-app#218]
Octave 4.4.1 has started freezing my MacBookPro completely when I try to launch the application, requiring a reboot.

I realise this is quite possibly not a bug in Octave itself but a corrupted file somewhere, but I wonder if anyone else has experienced this. 

If anyone can suggest how to resolve it I would really appreciate it, I've never had a system crash like this with any other software. 

I've been using Octave for about a month, with occasional crashes but I was able to use it until now.

I've tried uninstalling, reinstalling etc but no luck. 
Tried removing any residual config files remaining after uninstall but reinstall shows same issue.
Tried installing the previous version but that freezes the system too.

MacBookPro 2015, Mojave 10.14.6
Octave 4.4.1 u1;  
Octave 4.4.0;
(downloaded from https://octave-app.org/Download.html)

Many thanks for any help ...

ps: no criticism of the development behind Octave of course, I do appreciate how much work has gone into it

**Comment by apjanke** [comment]
Hi Douglas!

No idea how Octave.app could be causing a full system freeze. That is Not Supposed To Happen, and I haven't seen it myself. (My daily OS is also Mojave 10.14.6, on MacBook Pros and an iMac Pro.)

Could you try switching to the new Octave 6 Release Candidate, found here? https://github.com/octave-app/octave-app/releases/tag/v6.0.90-rc1

The Octave 6 build seems to solve several GUI stability problems we observed in the Octave 5 series; maybe it will help here, too.

**Comment by DouglasStrachan** [comment]
Many thanks Andrew I will give v6 a go and let you know

**Comment by DouglasStrachan** [comment]
Hello again Andrew,
I have tried the v6 download but unfortunately got the same result as with going back a version to v4.4.0 : the initial startup took a very long time, but they both did open & were usable. After that however, on re-opening those apps they freeze the system just as with v4.4.1u1

I think I am just blocked with this now and my current theory is it is not really to do with Octave itself.

Anyway if I get any more insight I will keep you posted.

And thanks again for your reply.

**Comment by DouglasStrachan** [comment]
ps not sure whether to close the issue or not : I guess nothing more we can do on it now

**Comment by apjanke** [comment]
Let's leave this open. Even though I don't have any ideas what to do about it, it's a problem, and we don't know for sure that it's _not_ Octave causing it, so we should mark it as a known issue, and maybe other users with the same problem, or even someone with an idea of how to fix it, will happen along here.

**Comment by lucifer9302** [comment]
@apjanke thank you so much. I tried a lot of people's tips but this one finally worked.
