### ISSUE TITLE
`pkg install communications` fails: hdf5 not found

### ISSUE THREAD

**Issue by NavneetKB** [octave-app/octave-app#219]
## Description
I am facing below error when i tried to install communications package using "pkg -forge install communications".

pkg: error running the configure script for communications.
error: called from
    configure_make at line 82 column 9
    install at line 184 column 7
    pkg at line 437 column 9

Replace this section with a description of the problem, including:
  * Tried to install communications package using "pkg -forge install communications".
  * Expected it to install smoothly
  * >> pkg install -forge -verbose communications
mkdir (/var/folders/x7/8lp22t_j2ns15sbfr11032ph0000gn/T/oct-3rxFkO)
untar (/Users/navneet/communications-1.2.2.tar.gz, /var/folders/x7/8lp22t_j2ns15sbfr11032ph0000gn/T/oct-3rxFkO)
checking for mkoctfile... /Applications/Octave-4.4.1.app/Contents/Resources/usr/Cellar/octave-octave-app@4.4.1/4.4.1/bin/mkoctfile-4.4.1 --verbose
checking for octave... /Applications/Octave-4.4.1.app/Contents/Resources/usr/Cellar/octave-octave-app@4.4.1/4.4.1/bin/octave-4.4.1
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether clang++ -std=gnu++11 accepts -g... yes
checking for a sed that does not truncate output... /Applications/Octave-4.4.1.app/Contents/Resources/usr/bin//gsed
checking   gripe_nonconformant or octave::err_nonconformant... octave::err_nonconformant
checking   gripe_wrong_type_arg or err_wrong_type_arg... err_wrong_type_arg
checking   gripe_square_matrix_required or err_square_matrix_required... err_square_matrix_required
checking   gripe_invalid_conversion or err_invalid_conversion... err_invalid_conversion
checking   gripe_implicit_conversion or warn_implicit_conversion... warn_implicit_conversion
checking   flush_octave_stdout or octave::flush_stdout... octave::flush_stdout
checking   is_complex_type or iscomplex... iscomplex
checking   is_real_type or isreal... isreal
checking   is_numeric_type or isnumeric... isnumeric
checking   is_empty or isempty... isempty
checking   oct_mach_info::float_format or octave::mach_info::float_format... octave::mach_info::float_format
checking how to run the C++ preprocessor... clang++ -std=gnu++11 -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking octave/oct.h usability... yes
checking octave/oct.h presence... yes
checking for octave/oct.h... yes
checking octave/base-lu.h usability... no
checking octave/base-lu.h presence... no
checking for octave/base-lu.h... no
checking octave/lu.h usability... yes
checking octave/lu.h presence... yes
checking for octave/lu.h... yes
checking octave/gripes.h usability... yes
checking octave/gripes.h presence... yes
checking for octave/gripes.h... yes
checking octave/errwarn.h usability... yes
checking octave/errwarn.h presence... yes
checking for octave/errwarn.h... yes
checking octave/ovl.h usability... yes
checking octave/ovl.h presence... yes
checking for octave/ovl.h... yes
checking octave/oct-obj.h usability... yes
checking octave/oct-obj.h presence... yes
checking for octave/oct-obj.h... yes
checking octave/ls-oct-ascii.h usability... no
checking octave/ls-oct-ascii.h presence... no
checking for octave/ls-oct-ascii.h... no
checking octave/ls-oct-text.h usability... yes
checking octave/ls-oct-text.h presence... yes
checking for octave/ls-oct-text.h... yes
checking for octave/oct-obj.h... (cached) yes
checking octave/interpreter.h usability... yes
checking octave/interpreter.h presence... yes
checking for octave/interpreter.h... yes
checking for pkg-config... /Applications/Octave-4.4.1.app/Contents/Resources/usr/bin//pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for HDF5... no
checking for H5Fopen in -lhdf5... no
configure: error: hdf5 not found

pkg: error running the configure script for communications.
error: called from
    configure_make at line 82 column 9
    install at line 184 column 7
    pkg at line 437 column 9

## Environment and Diagnostics

Please run `system env` in Octave.app, and copy & paste the output here:

```
>> system env
SHELL=/bin/zsh
TERM=xterm
TMPDIR=/var/folders/x7/8lp22t_j2ns15sbfr11032ph0000gn/T/
LC_NUMERIC=C
USER=navneet
COMMAND_MODE=unix2003
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.SrOyPWk4cB/Listeners
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
COLUMNS=119
PATH=/Applications/Octave-4.4.1.app/Contents/Resources/usr/bin/:/Applications/Octave-4.4.1.app/Contents/Resources/usr/bin/:/usr/local/sbin:/usr/local/opt/ruby/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Users/janke/.rvm/bin:/Applications/Octave-4.4.1.app/Contents/Resources/usr/Cellar/octave-octave-app@4.4.1/4.4.1/libexec/octave/4.4.1/site/exec/x86_64-apple-darwin16.7.0:/Applications/Octave-4.4.1.app/Contents/Resources/usr/Cellar/octave-octave-app@4.4.1/4.4.1/libexec/octave/api-v52/site/exec/x86_64-apple-darwin16.7.0:/Applications/Octave-4.4.1.app/Contents/Resources/usr/Cellar/octave-octave-app@4.4.1/4.4.1/libexec/octave/site/exec/x86_64-apple-darwin16.7.0:/Applications/Octave-4.4.1.app/Contents/Resources/usr/Cellar/octave-octave-app@4.4.1/4.4.1/libexec/octave/4.4.1/exec/x86_64-apple-darwin16.7.0:/Applications/Octave-4.4.1.app/Contents/Resources/usr/Cellar/octave-octave-app@4.4.1/4.4.1/bin
_=/usr/bin/env
__CFBundleIdentifier=org.octave-app.Octave
PWD=/Users/navneet/Documents
GS_OPTIONS=-sICCProfilesDir=/Applications/Octave-4.4.1.app/Contents/Resources/usr/opt/ghostscript/share/ghostscript/9.26/iccprofiles/ -sGenericResourceDir=/Applications/Octave-4.4.1.app/Contents/Resources/usr/opt/ghostscript/share/ghostscript/9.26/Resource/ -sFontResourceDir=/Applications/Octave-4.4.1.app/Contents/Resources/usr/opt/ghostscript/share/ghostscript/9.26/Resource/Font
LANG=en_IN.UTF-8
XPC_FLAGS=0x0
F77=/Applications/Octave-4.4.1.app/Contents/Resources/usr/bin/gfortran
LINES=58
XPC_SERVICE_NAME=0
HOME=/Users/navneet
SHLVL=2
FC=/Applications/Octave-4.4.1.app/Contents/Resources/usr/bin/gfortran
GNUTERM=qt
LOGNAME=navneet
DISPLAY=/private/tmp/com.apple.launchd.c95VG9dLFn/org.macosforge.xquartz:0
LC_TIME=C
ans = 0
```

If your problem is weird, please also run `octave_app_diagnostic_dump
[octave_app_diagnostic_dump.txt](https://github.com/octave-app/octave-app/files/5809800/octave_app_diagnostic_dump.txt)
` in Octave.app and attach its output file to this issue.

If your problem is Octave.app freezing with a spinning “beachball” mouse cursor, if you can, please take a spindump, zip it, and attach it to this issue. (To create a spindump, open Activity Monitor while Octave.app is frozen, select the `octave-gui` process, click the “gear” button in the upper left, and choose "Spindump".)

**Comment by apjanke** [comment]
That's strange. The `hdf5` package _is_ installed as part of Octave.app. The `communications` package must be having trouble detecting it somehow. I'll look in to it.

**Comment by apjanke** [comment]
Works for me in the shortly-upcoming Octave.app 6.1 release. Maybe something got fixed?

**Comment by apjanke** [comment]
Also weird: per https://github.com/octave-app/octave-app/issues/147, communications 1.2.2 was working for me under Octave.app 4.4.1 and 5.1. Hmmm...

**Comment by NavneetKB** [comment]
I am using Octave.app 4.4.1, which is latest available. And tried to install communication PKG using above mentioned command.

Still facing issue.

Please let me know if you need any further information to help resolve it.

**Comment by NavneetKB** [comment]
I can below hdf5 related things at location /Applications/Octave-4.4.1.app/Contents/Resources/usr/bin.

My OS is macOS BigSur version 11.1


lrwxr-xr-x    1 navneet  admin     32 May  6  2019 h52gif -> ../Cellar/hdf5/1.10.5/bin/h52gif
lrwxr-xr-x    1 navneet  admin     31 May  6  2019 h5c++ -> ../Cellar/hdf5/1.10.5/bin/h5c++
lrwxr-xr-x    1 navneet  admin     30 May  6  2019 h5cc -> ../Cellar/hdf5/1.10.5/bin/h5cc
lrwxr-xr-x    1 navneet  admin     33 May  6  2019 h5clear -> ../Cellar/hdf5/1.10.5/bin/h5clear
lrwxr-xr-x    1 navneet  admin     32 May  6  2019 h5copy -> ../Cellar/hdf5/1.10.5/bin/h5copy
lrwxr-xr-x    1 navneet  admin     33 May  6  2019 h5debug -> ../Cellar/hdf5/1.10.5/bin/h5debug
lrwxr-xr-x    1 navneet  admin     32 May  6  2019 h5diff -> ../Cellar/hdf5/1.10.5/bin/h5diff
lrwxr-xr-x    1 navneet  admin     32 May  6  2019 h5dump -> ../Cellar/hdf5/1.10.5/bin/h5dump
lrwxr-xr-x    1 navneet  admin     30 May  6  2019 h5fc -> ../Cellar/hdf5/1.10.5/bin/h5fc
lrwxr-xr-x    1 navneet  admin     42 May  6  2019 h5format_convert -> ../Cellar/hdf5/1.10.5/bin/h5format_convert
lrwxr-xr-x    1 navneet  admin     34 May  6  2019 h5import -> ../Cellar/hdf5/1.10.5/bin/h5import
lrwxr-xr-x    1 navneet  admin     31 May  6  2019 h5jam -> ../Cellar/hdf5/1.10.5/bin/h5jam
lrwxr-xr-x    1 navneet  admin     30 May  6  2019 h5ls -> ../Cellar/hdf5/1.10.5/bin/h5ls
lrwxr-xr-x    1 navneet  admin     33 May  6  2019 h5mkgrp -> ../Cellar/hdf5/1.10.5/bin/h5mkgrp
lrwxr-xr-x    1 navneet  admin     39 May  6  2019 h5perf_serial -> ../Cellar/hdf5/1.10.5/bin/h5perf_serial
lrwxr-xr-x    1 navneet  admin     36 May  6  2019 h5redeploy -> ../Cellar/hdf5/1.10.5/bin/h5redeploy
lrwxr-xr-x    1 navneet  admin     34 May  6  2019 h5repack -> ../Cellar/hdf5/1.10.5/bin/h5repack
lrwxr-xr-x    1 navneet  admin     34 May  6  2019 h5repart -> ../Cellar/hdf5/1.10.5/bin/h5repart
lrwxr-xr-x    1 navneet  admin     32 May  6  2019 h5stat -> ../Cellar/hdf5/1.10.5/bin/h5stat
lrwxr-xr-x    1 navneet  admin     33 May  6  2019 h5unjam -> ../Cellar/hdf5/1.10.5/bin/h5unjam
lrwxr-xr-x    1 navneet  admin     33 May  6  2019 h5watch -> ../Cellar/hdf5/1.10.5/bin/h5watch

**Comment by NavneetKB** [comment]
/Applications/Octave-4.4.1.app/Contents/Resources/usr/Cellar/hdf5/1.10.5

Even though hdf5 is located with in Octave app.
Still facing issue.

**Comment by apjanke** [comment]
> My OS is macOS BigSur version 11.1

Ah, this could be related: I haven't tested Octave.app on Big Sur yet. I'll set up a VM to do so.

**Comment by NavneetKB** [comment]
Did you too observe it on BigSur?

**Comment by NavneetKB** [comment]
I am still facing this issue on latest Octave for MAC. Please help if you get anything.

**Comment by eric248550** [comment]
I am facing this problem now, is there any solution?

**Comment by siko1056** [comment]
Recently a user had success on this issue, see at Octave Discourse:

https://octave.discourse.group/t/error-installing-the-communications-package-on-macos-octave-6-3-0/1746/6

**Comment by ruchitrajhansa** [comment]
This error still persists with the new 6.3.0 beta1 of Octave.app

**Comment by apjanke** [comment]
Sorry, folks: everything is currently totally borked with the 6.3.x Octave builds, because I insist on sticking with macOS 10.14.x for my main computers, and Homebrew no longer supports that. (I also have 10.15 and 11.0 VMs, and I still can't get the Octave.app build to run on them at the moment, and I'm exhausted.)

I'm going to take a long nap and try to pick this up over the weekend.

**Comment by phil61** [comment]
Hi all,

I ran into the same problem installing Communications 1.2.4 on Octave 6.2.0 on MacOS 11.6.3 (Big Sur) today.

Rather than installing the Homebrew version of hdf5, I simply modified the instructions posted by @siko1056 to point to the hdf5 installation actually embedded in the Octave-6.2.0.app:

> setenv('CPPFLAGS', '-I/Applications/Octave-6.2.0.app/Contents/Resources/usr/opt/hdf5/include')
> setenv('LDFLAGS', '-L/Applications/Octave-6.2.0.app/Contents/Resources/usr/opt/hdf5/lib')

followed by:

> pkg install -forge -verbose communications

Despite a warning near the end of the installation script referencing unusable help text found on 'commsimages', it installed correctly.

Short of the package maintainer for Communications fixing the installation, this workaround will at least use the intended hdf5 package...

p.s. Cross-posted from:https://octave.discourse.group/t/trouble-installing-the-communications-package-on-macos-homebrew-again/1746/23

**Comment by aleguillen4** [comment]
Hi all,
I ran into the same problem installing Communications 1.2.4 on Octave 6.4.0 on Ubuntu 22.04.1 LTS. 
When I try to run 

- pkg install -forge -verbose communications
-  pkg install "https://downloads.sourceforge.net/project/octave/Octave%20Forge%20Packages/Individual%20Package%20Releases/communications-1.2.4.tar.gz"
I get the output:
`mkdir (/tmp/oct-OBJynP)
untar (/tmp/communications-1.2.4-vD0HoX.tar.gz, /tmp/oct-OBJynP)
checking for mkoctfile... /usr/bin/mkoctfile --verbose
checking for octave... /usr/bin/octave
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for a sed that does not truncate output... /usr/bin/sed
checking   gripe_nonconformant or octave::err_nonconformant... octave::err_nonconformant
checking   gripe_wrong_type_arg or err_wrong_type_arg... err_wrong_type_arg
checking   gripe_square_matrix_required or err_square_matrix_required... err_square_matrix_required
checking   gripe_invalid_conversion or err_invalid_conversion... err_invalid_conversion
checking   gripe_implicit_conversion or warn_implicit_conversion... warn_implicit_conversion
checking   flush_octave_stdout or octave::flush_stdout... octave::flush_stdout
checking   is_complex_type or iscomplex... iscomplex
checking   is_real_type or isreal... isreal
checking   is_numeric_type or isnumeric... isnumeric
checking   is_empty or isempty... isempty
checking   oct_mach_info::float_format or octave::mach_info::float_format... octave::mach_info::float_format
checking how to run the C++ preprocessor... g++ -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking octave/oct.h usability... yes
checking octave/oct.h presence... yes
checking for octave/oct.h... yes
checking octave/base-lu.h usability... no
checking octave/base-lu.h presence... no
checking for octave/base-lu.h... no
checking octave/lu.h usability... yes
checking octave/lu.h presence... yes
checking for octave/lu.h... yes
checking octave/gripes.h usability... no
checking octave/gripes.h presence... no
checking for octave/gripes.h... no
checking octave/errwarn.h usability... yes
checking octave/errwarn.h presence... yes
checking for octave/errwarn.h... yes
checking octave/ovl.h usability... yes
checking octave/ovl.h presence... yes
checking for octave/ovl.h... yes
checking octave/oct-obj.h usability... no
checking octave/oct-obj.h presence... no
checking for octave/oct-obj.h... no
checking octave/ls-oct-ascii.h usability... no
checking octave/ls-oct-ascii.h presence... no
checking for octave/ls-oct-ascii.h... no
checking octave/ls-oct-text.h usability... yes
checking octave/ls-oct-text.h presence... yes
checking for octave/ls-oct-text.h... yes
checking for octave/oct-obj.h... (cached) no
checking octave/interpreter.h usability... yes
checking octave/interpreter.h presence... yes
checking for octave/interpreter.h... yes
checking for pkg-config... no
checking for hdf5... no
checking for H5Fopen in -lhdf5... no
configure: error: hdf5 not found

error: pkg: error running the configure script for communications.
error: called from
    configure_make at line 93 column 9
    install at line 198 column 7
    pkg at line 568 column 9`

If I run system env I get 
`LESSOPEN=| /usr/bin/lesspipe %s
USER=alejandro7570
LC_TIME=C
XDG_SESSION_TYPE=wayland
SHLVL=1
HOME=/home/alejandro7570
DESKTOP_SESSION=ubuntu
GNOME_SHELL_SESSION_MODE=ubuntu
GTK_MODULES=gail:atk-bridge
LC_MONETARY=es_CR.UTF-8
SYSTEMD_EXEC_PID=1658
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
COLORTERM=truecolor
IM_CONFIG_PHASE=1
WAYLAND_DISPLAY=wayland-0
LOGNAME=alejandro7570
_=/usr/bin/octave
XDG_SESSION_CLASS=user
USERNAME=alejandro7570
TERM=xterm
COLUMNS=112
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/usr/libexec/octave/6.4.0/site/exec/x86_64-pc-linux-gnu:/usr/libexec/octave/api-v56/site/exec/x86_64-pc-linux-gnu:/usr/libexec/octave/site/exec/x86_64-pc-linux-gnu:/usr/libexec/octave/6.4.0/exec/x86_64-pc-linux-gnu:/usr/bin
SESSION_MANAGER=local/alejandro7570-Inspiron-7570:@/tmp/.ICE-unix/1627,unix/alejandro7570-Inspiron-7570:/tmp/.ICE-unix/1627
XDG_MENU_PREFIX=gnome-
LC_ADDRESS=es_CR.UTF-8
GNOME_TERMINAL_SCREEN=/org/gnome/Terminal/screen/1849c254_30e6_4cd3_8daa_1676a5a1f565
GNOME_SETUP_DISPLAY=:1
XDG_RUNTIME_DIR=/run/user/1000
DISPLAY=:0
LANG=en_US.UTF-8
XDG_CURRENT_DESKTOP=ubuntu:GNOME
LC_TELEPHONE=es_CR.UTF-8
XMODIFIERS=@im=ibus
XDG_SESSION_DESKTOP=ubuntu
XAUTHORITY=/run/user/1000/.mutter-Xwaylandauth.OQH501
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
GNOME_TERMINAL_SERVICE=:1.138
SSH_AGENT_LAUNCHER=gnome-keyring
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
SHELL=/bin/bash
LC_NAME=es_CR.UTF-8
QT_ACCESSIBILITY=1
GDMSESSION=ubuntu
LESSCLOSE=/usr/bin/lesspipe %s %s
LC_MEASUREMENT=es_CR.UTF-8
LC_IDENTIFICATION=es_CR.UTF-8
QT_IM_MODULE=ibus
PWD=/home/alejandro7570
XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/etc/xdg
XDG_DATA_DIRS=/usr/share/ubuntu:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
LC_NUMERIC=C
LINES=52
LC_PAPER=es_CR.UTF-8
VTE_VERSION=6800
ans = 0`
Can someone help me giving the setenv command to octave? I looked at the files inside usr/include/octave-6.4.0/octave and I couldn't find a lib or include folder.

**Comment by apjanke** [comment]
@aleguillen4 Hi! I'm afraid you're in the wrong repo here. Octave.app is the "native" Mac distribution of GNU Octave. We're a special packaging project, and not the main GNU Octave project itself. We don't do Linux or Windows. For Linux stuff, you want to talk to the main GNU Octave maintainers, which you can do at https://octave.discourse.group/.

**Comment by aleguillen4** [comment]
> @aleguillen4 Hi! I'm afraid you're in the wrong repo here. Octave.app is the "native" Mac distribution of GNU Octave. We're a special packaging project, and not the main GNU Octave project itself. We don't do Linux or Windows. For Linux stuff, you want to talk to the main GNU Octave maintainers, which you can do at https://octave.discourse.group/.

Thank you for your advice!
Today I figured out that my problem was that I didn't have pkg-config, with
```
sudo apt-get update
sudo apt-get install pkg-config
```
I managed to solve my problem.

**Comment by apjanke** [comment]
I think this is fixed in newer Octave.app releases, like [8.4.0](https://github.com/octave-app/octave-app/releases/tag/v8.4.0) and [9.2.0 beta1](https://github.com/octave-app/octave-app/releases/tag/v9.2.0_beta1). In those, a plain `pkg install -forge communications` works for me, and the package test suite passes.

E.g., in Octave.app 8.4.0 on my macOS 14.5 Intel box today:

```
>> pkg install -forge communications
ld: warning: duplicate -bundle_loader option, '/Applications/Octave-8.4.0.app/Contents/Resources/usr/Cellar/octave-octapp@8.4.0/8.4.0/bin/octave-8.4.0' ignored
[...]
ld: warning: duplicate -bundle_loader option, '/Applications/Octave-8.4.0.app/Contents/Resources/usr/Cellar/octave-octapp@8.4.0/8.4.0/bin/octave-8.4.0' ignored
For information about changes from previous versions of the communications package, run 'news communications'.
>> pkg load communications
>> runtests2 -pkg communications
  /Users/janke/Library/Application Support/Octave.app/8.4.0/pkg/communications-1.2.6/@galois/conv.m  PASS      2/2
  /Users/janke/Library/Application Support/Octave.app/8.4.0/pkg/communications-1.2.6/@galois/deconv.m  PASS      2/2
  /Users/janke/Library/Application Support/Octave.app/8.4.0/pkg/communications-1.2.6/@galois/dftmtx.m  PASS      2/2
[...]

Summary:

  GNU Octave Version: 8.4.0 (hg id: 78c13a2594f3 + patches)
  Tests run on angharad.local (macOS) at 04-Jul-2024 09:11:30
  Test execution time: 00:01:14

  PASS                              581
  FAIL                                0
  XFAIL (reported bug)                6
```

I'm calling this Fixed. Please re-open this issue if it's still happening with newer Octave.app releases.
