### ISSUE TITLE
Shall we add Sundials 3 support?

### ISSUE THREAD

**Issue by schoeps** [octave-app/octave-app#22]
Bug report https://savannah.gnu.org/bugs/?52475 has produced the commit http://hg.savannah.gnu.org/hgweb/octave/rev/d94876e7a0aa which allows using sundials 3. This would allow us to avoid the shipping of the old version 2. Shall we jump or wait?

**Comment by apjanke** [comment]
I say wait. They explicitly said they're keeping Octave 5.1.0 at Sundials 2.7 compatibility: https://savannah.gnu.org/bugs/?52475#comment74. I don't think we should diverge from upstream here.

I have already [bumped Sundials up to Sundials 4.x on the `octave-default` formula](https://github.com/octave-app/homebrew-octave-app/commit/233f409a5b2c6baf954509c96c4d6213932312e1) which tracks the default development branch. We can pick it up with Octave 5.2 or 6.0.

**Comment by apjanke** [comment]
Closing this as "waiting until next release".
