### ISSUE TITLE
/home/user/.config/octave/qt-octave-gui.ini does not exist

### ISSUE THREAD

**Issue by CharlesShan-hub** [octave-app/octave-app#224]
## Description
When installed and open the app. It jumped like this:
```
The settings file /home/user/.config/octave/octave-gui.ini does not exist and can not be created. Make sure you have read and write permissions to /home/user/.config/octave Octave GUI must be closed now.
```
Finally, I found the way to solve the problem. I met the problem because I installed the Octave on Mac by "brew", and then I uninstall and loaded the dmg file. The folder /home/user/.config/octave still exist, when I reinstalled the Octave. After I delete the folder /home/user/.config/octave and restart Octave. It run!

## Environment 
Mac Catalina 10.15.7

(PS: the problem has solved, I write here in the hope that I can help others who are in the same predicament.)

**Comment by apjanke** [comment]
Well crap. That's a surprising one to me: I would think that if `~/.config/octave/` were created by the Homebrewed Octave, then either `~/.config/octave/octave-gui.ini` would exist, or `~/.config/octave/` would be writable by you, so `octave` from Octave.app could create the file itself.

Maybe a bug in upstream Octave, actually? Octave.app's packaging stuff does not directly mess around with `~/.config/octave/octave-gui.ini`, AFAIK.

**Comment by apjanke** [comment]
BTW, thanks for the bug report, even though you found a workaround! It's helpful to have stuff like this on the public record and know how other users solved it.

**Comment by apjanke** [comment]
Closing as Resolved, since OP reports it's working. This ticket will remain around and searchable in its Closed state.
