### ISSUE TITLE
MacOS Big Sur Issue during Installing

### ISSUE THREAD

**Issue by AlexLir20** [octave-app/octave-app#226]
## MacOS Big Sur Issue during Installing

Open Octave with quitting unexpectedly

![image](https://user-images.githubusercontent.com/86774470/124101215-08d32f80-da57-11eb-8683-f5c7a0ffbe69.png)

**Comment by VivianLin98** [comment]
I got the same issue when trying to install both octave-6.2.0 and octave-6.0.90. Do you solve this problem?

**Comment by apjanke** [comment]
Closing this ticket as old / can't-reproduce. If you have problems with the more recent releases, please re-open, or open a new ticket.
