### ISSUE TITLE
Octave 6.3.0 build

### ISSUE THREAD

**Issue by stevemaser** [octave-app/octave-app#229]
Hey all...

We pull down Octave from:  https://octave-app.org  for deployment here on our Macs.   Any ETA on a 6.3.0 installer?   Thanks so much!

**Comment by stevemaser** [comment]
I only tested that it launched.   I don't personally use it, so I wouldn't have caught any operational bugs.

**Comment by apjanke** [comment]
I ran the test suite and it came out fine, so it looks good to me. Just need to be able to get an actual non-beta build done...

**Comment by apjanke** [comment]
Oh, just to be clear: that "well crap" error I posted is from the Octave.app _build_, not while running it. So I currently can't make a non-beta build at all.

**Comment by apjanke** [comment]
Darnit. Now we've got another problem: Some of the Homebrewed build tools we use are now broken on macOS 10.13 and 10.14: https://github.com/octave-app/octave-app/issues/234

**Comment by stevemaser** [comment]
(Hey, also, from our end, we don't support anything less than 10.15 now -- if that matters...)

**Comment by apjanke** [comment]
I'd really like to continue supporting at least 10.14, and preferably 10.13, with Octave.app. Two reasons:

a) We don't do any analytics or user tracking, so we have no idea what OS versions our user base is running, but I have at least some anecdotal reports that some Octave.app users are still on older OSes.
b) I personally am stuck on macOS 10.14 (because I am an Aperture user), and I'd like to be able to run my own software project. ;)

I guess that doesn't stop me from rolling out 10.15-required 6.3.0/6.4.0 builds as a provisional measure until I can get 10.13/10.14 support fixed up, though. I'll give this a try tonight!

**Comment by apjanke** [comment]
Currently stalled due to upstream issue because the Homebrew ghostscript build is broken: https://github.com/Homebrew/brew/issues/12550

**Comment by apjanke** [comment]
Homebrew ghostscript is fixed. Now it's busted because Qt 5.15.2 doesn't want to build on macOS 10.15. Might be fixable by just bumping the Qt version.

```
==> ./configure -verbose -prefix /Applications/Octave-6.3.0.app/Contents/Resources/usr/Cellar/qt-octave-app/5.15
==> make
Last 15 lines from /Users/janke/Library/Logs/Homebrew/qt-octave-app/02.make:
  File "/private/tmp/qt-octave-app-20211211-3079-1y33sbp/qt-everywhere-src-5.15.2/qtwebengine/src/3rdparty/chromium/build/mac/find_sdk.py", line 96, in main
    raise Exception('No %s+ SDK found' % min_sdk_version)
Exception: No 11.1+ SDK found

See //components/nacl/features.gni:9:3: whence it was imported.
  import("//build/config/mac/mac_sdk.gni")
  ^--------------------------------------
See //BUILD.gn:18:1: whence it was imported.
import("//components/nacl/features.gni")
^--------------------------------------
Project ERROR: GN run error!
make[3]: *** [sub-gn_run-pro-make_first] Error 3
make[2]: *** [sub-core-make_first] Error 2
make[1]: *** [sub-src-make_first] Error 2
make: *** [module-qtwebengine-make_first] Error 2
```

**Comment by apjanke** [comment]
Octave.app 8.4 is coming soon! It's building OK, and prerelease alpha builds are up for testing now ([here's alpha3](https://github.com/octave-app/octave-app/releases/tag/v8.4.0_alpha3)), including a new native Apple Silicon build.

Progress tracking for 8.x is over on this ticket: https://github.com/octave-app/octave-app/issues/243. Closing this here ticket as being subsumed by that one; please check over there for further updates. I currently expect a beta prelrease this weekend and the golden release probably next weekend.
