### ISSUE TITLE
Octave.app for 6.2.0 GUI Not Working

### ISSUE THREAD

**Issue by JensenKaplan** [octave-app/octave-app#232]
## Description
I installed the app for  6.2.0 I let it bypass the Gatekeeper. When using the app it would open an Octave terminal, no GUI. In the top lines it looked like it called the GUI then exit immediately after wards. Here's the terminal when it first opens:

<img width="567" alt="Screen Shot 2021-11-11 at 9 32 23 PM" src="https://user-images.githubusercontent.com/65718701/141410505-acbdb594-37a4-442c-940b-7be37be39fba.png">

```
Last login: Thu Nov 11 23:12:59 on ttys000
/Applications/Octave-6.2.0.app/Contents/Resources/usr/Cellar/octave-octave-app@6.2.0/6.2.0/libexec/octave/6.2.0/exec/x86_64-apple-darwin18.7.0/octave-gui ; exit;
/Users/jensenkaplan/.zprofile:1: no such file or directory: /opt/homebrew/bin/brew
(base) jensenkaplan@Jensens-MacBook-Pro ~ % /Applications/Octave-6.2.0.app/Contents/Resources/usr/Cellar/octave-octave-app@6.2.0/6.2.0/libexec/octave/6.2.0/exec/x86_64-apple-darwin18.7.0/octave-gui ; exit;
GNU Octave, version 6.2.0
Copyright (C) 2021 The Octave Project Developers.
This is free software; see the source code for copying conditions.
There is ABSOLUTELY NO WARRANTY; not even for MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  For details, type 'warranty'.

Octave was configured for "x86_64-apple-darwin18.7.0".

Additional information about Octave is available at https://www.octave.org.

Please contribute if you find this software useful.
For more information, visit https://www.octave.org/get-involved.html

Read https://www.octave.org/bugs.html to learn how to submit bug reports.
For information about changes from previous versions, type 'news'.

octave:1> 
```

## Environment and Diagnostics

Please run `system env` in Octave.app, and copy & paste the output here:

```
TERM_PROGRAM=Apple_Terminal
SHELL=/bin/zsh
TERM=xterm-256color
TMPDIR=/var/folders/vq/mmg58sj542vb8d603nwpj5j00000gn/T/
CONDA_SHLVL=1
CONDA_PROMPT_MODIFIER=(base) 
TERM_PROGRAM_VERSION=443
LC_NUMERIC=C
TERM_SESSION_ID=C0B87A05-0B87-4E29-A9EE-8B6DA051E653
USER=jensenkaplan
CONDA_EXE=/opt/anaconda3/bin/conda
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.rLHgF3CV8b/Listeners
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
COLUMNS=80
_CE_CONDA=
PATH=/opt/anaconda3/bin:/opt/anaconda3/condabin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/jensenkaplan/Library/Python/3.8/bin:/Applications/Octave-6.2.0.app/Contents/Resources/usr/Cellar/octave-octave-app@6.2.0/6.2.0/libexec/octave/6.2.0/site/exec/x86_64-apple-darwin18.7.0:/Applications/Octave-6.2.0.app/Contents/Resources/usr/Cellar/octave-octave-app@6.2.0/6.2.0/libexec/octave/api-v55/site/exec/x86_64-apple-darwin18.7.0:/Applications/Octave-6.2.0.app/Contents/Resources/usr/Cellar/octave-octave-app@6.2.0/6.2.0/libexec/octave/site/exec/x86_64-apple-darwin18.7.0:/Applications/Octave-6.2.0.app/Contents/Resources/usr/Cellar/octave-octave-app@6.2.0/6.2.0/libexec/octave/6.2.0/exec/x86_64-apple-darwin18.7.0:/Applications/Octave-6.2.0.app/Contents/Resources/usr/Cellar/octave-octave-app@6.2.0/6.2.0/bin
_=/usr/bin/env
CONDA_PREFIX=/opt/anaconda3
__CFBundleIdentifier=com.apple.Terminal
PWD=/Users/jensenkaplan
LANG=en_US.UTF-8
XPC_FLAGS=0x0
LINES=24
_CE_M=
XPC_SERVICE_NAME=0
SHLVL=2
HOME=/Users/jensenkaplan
CONDA_PYTHON_EXE=/opt/anaconda3/bin/python
LOGNAME=jensenkaplan
CONDA_DEFAULT_ENV=base
LC_TIME=C
ans = 0
```
## Diagnostic dump

[octave_app_diagnostic_dump.txt](https://github.com/octave-app/octave-app/files/7524944/octave_app_diagnostic_dump.txt)

**Comment by apjanke** [comment]
That's kind of weird. I think this is the first time we've seen this particular behavior. We've hardly had any testing on macOS 12 Monterey, though, and I don't have a Monterey VM to test on.

Just in case, could you also try the 6.3.0 beta found here? https://github.com/octave-app/octave-app/releases/tag/v6.3.0-beta1

**Comment by JensenKaplan** [comment]
Hey thanks for the response. Unfortunately does the same thing on 6.3.0.

**Comment by apjanke** [comment]
Well shoot. Time for some debugging.

Sorry if this is going to take a bit. I'm trying to get the 6.3.0 and 6.4.0 releases rolled first, and then I can work on building up a macOS 12 testing environment.

**Comment by JensenKaplan** [comment]
Alright, I appreciate it.
Taking Andrew Ng's ML course. Started on my windows desktop then got the
new MacBook pro. Unfortunately for now I'll have to use Matlab.
I appreciate the response.

Jensen

**Comment by stevemaser** [comment]
FWIW -- 6.2.0 still launches on my Intel and M1 macs running 12.1 without issue.   (As mentioned before, I'm just responsible for making sure it installs around here -- not actually using it...)

**Comment by ejsdy** [comment]
Hello! Got the same concern as JensenKaplan, I also noticed that the .config folder on my mac doesnt contain the octave folder when I install it. Any way this can be fixed?

**Comment by apjanke** [comment]
I think the `~/.config/octave` (or `~/.local/octave`) folder should automatically appear as soon as it is used, for example, when you do a user-level `pkg install`. Is `pkg install` working for you under octave.app?

**Comment by ejsdy** [comment]
Whenever I run the app, it keeps telling me that I have started it for the first time when I have already opened it more than once. I have already reinstalled it and the same thing happens.

I am also not sure where I should do the `pkg install`?

**Comment by apjanke** [comment]
>  it keeps telling me that I have started it for the first time when I have already opened it more than once

Oh! Yeah, that looks like an issue here. Let me dig around the source and see exactly what file it's looking for. That might be under `~/.config/octave`, or it might be under the more Mac-like `~/Library/Application Support/Octave.app/<version>`.

**Comment by apjanke** [comment]
`pkg install` is a command you do from the Octave command window once it's running. And for Octave.app, the files installed there will go to `~/Library/Application Support/Octave.app/<version>/pkg` – this location customization allows you to run multiple versions of Octave.app side-by-side on the same machine.

**Comment by ejsdy** [comment]
Thank you! 

There's also no Octave.app or Octave folder on my Application Support folder.

Ahh yes, the GUI isn't running on my end so I can't exactly input `pkg install` anywhere?

**Comment by apjanke** [comment]
> There's also no Octave.app or Octave folder on my Application Support folder.

That probably won't appear until you do a `pkg install` command; I don't think it's used for anything else.

> Ahh yes, the GUI isn't running on my end so I can't exactly input pkg install anywhere?

If you've got a terminal-mode Octave running, like this:

```text
GNU Octave, version 6.2.0
Copyright (C) 2021 The Octave Project Developers.
This is free software; see the source code for copying conditions.
There is ABSOLUTELY NO WARRANTY; not even for MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  For details, type 'warranty'.

Octave was configured for "x86_64-apple-darwin18.7.0".

Additional information about Octave is available at https://www.octave.org.

Please contribute if you find this software useful.
For more information, visit https://www.octave.org/get-involved.html

Read https://www.octave.org/bugs.html to learn how to submit bug reports.
For information about changes from previous versions, type 'news'.

octave:1>
octave:1>
```

Then you can run `pkg` or other Octave commands from that `octave:N>` prompt, and it'll have the same effect. But I think the `pkg` and `~/Library/Application Support/Octave.app` may be a red herring here, and the "first-run" stuff is looking for `~/.config/octave` or something like that.

**Comment by ejsdy** [comment]
I also put `pkg install -forge octave` and still nothing happens

**Comment by ejsdy** [comment]
Ohh it worked when I asked for the .ini file from another user and put it manually in the .config folder!

**Comment by apjanke** [comment]
> When I input 'pkg' on the octave terminal it crashes and says that octave-gui quit unexpectedly

Ouch. That's not what's supposed to happen.

> I also put `pkg install -forge octave` and still nothing happens

There's no Octave Forge package named "octave". Try `pkg install -forge io`. I'm currently getting web or network read errors like this for any package, and that's probably a separate issue:

```text
>> pkg install -forge io
error: get_forge_pkg: could not read URL, please verify internet connection
error: called from
    get_forge_pkg at line 72 column 7
    get_forge_download at line 32 column 14
    pkg at line 500 column 31
```

**Comment by apjanke** [comment]
> Ohh it worked when I asked for the .ini file from another user and put it manually in the .config folder!

Hrmmm. I'm gonna have to look at the source code for this one. Sorry!

**Comment by apjanke** [comment]
There's new Octave.app [8.4.0](https://github.com/octave-app/octave-app/releases/tag/v8.4.0) and [9.2.0 beta1](https://github.com/octave-app/octave-app/releases/tag/v9.2.0_beta1) releases out. Could you check and see if those work for you? Not a whole lot to do for older releases like 6.x at this point.

**Comment by apjanke** [comment]
Don't know if there's anything else to do here, since this ticket is for an older version, and a bit nebulous. Closing as "probably fixed in newer versions". Please re-open, or create a new issue, if you're still having problems with newer Octave.app releases.
