### ISSUE TITLE
Failed to install package control: "checking whether the C++ compiler works... no" 

### ISSUE THREAD

**Issue by rodrigoarnabal** [octave-app/octave-app#233]
## Description

I am new with Octave. I recently installed Octave 6.2.0.

 I want to use Dyanre 4.6.4with it on a Mac running 12.0.1. 

When try to install packages to run Dynare I get the following message:

>> pkg install -forge io statistics control struct optim
configure: error: in `/var/folders/ys/s63m8c2d5h7_g9sw0gc8v3tm0000gn/T/oct-445Op0/control-3.3.1/src':
configure: error: C++ compiler cannot create executables
See `config.log' for more details
checking for mkoctfile... /Applications/Octave-6.2.0.app/Contents/Resources/usr/Cellar/octave-octave-app@6.2.0/6.2.0/bin/mkoctfile-6.2.0
checking for octave-config... /Applications/Octave-6.2.0.app/Contents/Resources/usr/Cellar/octave-octave-app@6.2.0/6.2.0/bin/octave-config-6.2.0
checking whether the C++ compiler works... no

**Comment by apjanke** [comment]
Looks like you might not have Xcode or the Xcode Command Line Tools installed. Those are required to compile programs on macOS, including Octave packages which have native extensions. Try running `sudo xcode-select --install` from the Terminal to install the Xcode CLT, and then restart Octave.app and try installing this package again.

**Comment by apjanke** [comment]
Closing this as "probably a user env configuration problem". Looks like this was just Xcode / Xcode CLT not being installed. Those are what provide clang on macOS.

If you're having trouble with this on a Mac that does have Xcode CLT installed, please re-open this issue, and attach the output of `octapp.diagnostic_dump` (to help figure out what your compiler setup is).
