### ISSUE TITLE
Fail to install control package

### ISSUE THREAD

**Issue by richarddallier** [octave-app/octave-app#235]
Hello,
Working on macos. I tried to install the control package from forge with 
pkg install -forge control
but I get the following error message:

>> pkg install -forge control
sh: gfortran: command not found
sh: gfortran: command not found
make: *** [slicotlibrary.a] Error 127
make: *** Waiting for unfinished jobs....
tar -xzf slicot.tar.gz
/usr/local/Cellar/octave/6.4.0_1/bin/mkoctfile-6.4.0 -Wall -Wno-deprecated-declarations  __control_helper_functions__.cc
mkdir sltmp
mv slicot/src/*.f ./sltmp
mv slicot/src_aux/*.f ./sltmp
if [ "0" = "1" ]; then \
                echo "copy routines using DGGES"; \
                cp SB04OD.fortran ./sltmp/SB04OD.f; \
                cp SG03AD.fortran ./sltmp/SG03AD.f; \
                cp SG03BD.fortran ./sltmp/SG03BD.f; \
        fi;
cp AB08NX.fortran ./sltmp/AB08NX.f
cp AG08BY.fortran ./sltmp/AG08BY.f
cp SB01BY.fortran ./sltmp/SB01BY.f
cp SB01FY.fortran ./sltmp/SB01FY.f
cp SB06ND.fortran ./sltmp/SB06ND.f
cp TB01MD.fortran ./sltmp/TB01MD.f
cp TB01ND.fortran ./sltmp/TB01ND.f
cp TB01ZD.fortran ./sltmp/TB01ZD.f
cp TG04BX.fortran ./sltmp/TG04BX.f
cp ODLTZM.fortran ./sltmp/ODLTZM.f
cp makefile.slicot ./sltmp/makefile
cd sltmp; /usr/local/Cellar/octave/6.4.0_1/bin/mkoctfile-6.4.0 -w -c MA02ID.f; rm MA02ID.f; /usr/local/Cellar/octave/6.4.0_1/bin/mkoctfile-6.4.0 -c *.f;

error: pkg: error running 'make' for the control package.
error: called from
    configure_make at line 110 column 9
    install at line 196 column 7
    pkg at line 568 column 9

This makes me think that I have an environment problem. The command "which gfortran" gives 
/usr/local/bin/gfortran

Anyone can help ?
Thanks

## Environment and Diagnostics

>> system env
SHELL=/bin/zsh
TERM=xterm
TMPDIR=/var/folders/jm/_xdyfjpd5b3_781vf7jsd_hc0000gp/T/
LC_NUMERIC=C
USER=dallier
COMMAND_MODE=unix2003
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.8c3tJTVtAQ/Listeners
__CF_USER_TEXT_ENCODING=0x1F6:0x0:0x1
COLUMNS=135
PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Cellar/octave/6.4.0_1/libexec/octave/6.4.0/site/exec/x86_64-apple-darwin20.6.0:/usr/local/Cellar/octave/6.4.0_1/libexec/octave/api-v56/site/exec/x86_64-apple-darwin20.6.0:/usr/local/Cellar/octave/6.4.0_1/libexec/octave/site/exec/x86_64-apple-darwin20.6.0:/usr/local/Cellar/octave/6.4.0_1/libexec/octave/6.4.0/exec/x86_64-apple-darwin20.6.0:/usr/local/Cellar/octave/6.4.0_1/bin
_=/usr/bin/env
__CFBundleIdentifier=com.apple.ScriptEditor.id.Octave
PWD=/Users/dallier
ZES_ENABLE_SYSMAN=1
XPC_FLAGS=0x0
LINES=90
XPC_SERVICE_NAME=0
HOME=/Users/dallier
SHLVL=2
GNUTERM=qt
LOGNAME=dallier
DISPLAY=/private/tmp/com.apple.launchd.WscWrlYA6T/org.xquartz:0
LC_TIME=C
ans = 0

**Comment by apjanke** [comment]
Hi, richard!

It looks like you're running a regular Homebrew-installed Octave, not Octave.app. Octave.app is a special Octave distribution that lives in /Applications, not /usr/local/Cellar. (Also we don't have a 6.4.0 release yet.)

Anyway, looks like this is a path problem. Your gfortran is in /usr/local/bin, but I don't see /usr/local/bin in the PATH in your environment dump. Looks like however you're running Octave here isn't picking up whatever shell startup scripts or whatever are getting /usr/local/bin on your path.

This is something you could ask about on the general Octave Discourse at https://octave.discourse.group/.

**Comment by richarddallier** [comment]
Thanks Andrew! I'm running Octave through an applescript file which contains only:
do shell script "/usr/local/bin/octave --gui"
so as the GUI is launched and I can also have it like an Apple app in my Application folder. I guess I just have to add my /usr/local/bin to the PATH listed in the "system env" results, but I don't know which PATH it is (anyway, different from my own local PATH environment variable obtained when echoing it in a terminal). I'm ok to forward the discussion to the discourse group, but maybe it won't be necessary if you can tell me what PATH is listed within Octave and where/when it is defined.

**Comment by apjanke** [comment]
Like, are you running that AppleScript file by double-clicking it or otherwise launching it from the Finder or Spotlight? If so, that's probably your problem: AppleScript sessions, and the programs they call, do not call your `~/.bashrc` and other shell startup files, so they don't get your special environment configuration that you see when you launch a Terminal session, and that's where you pick up `/usr/local/bin` for your `$PATH` environment variable, because it's not on the PATH by default.

So you could modify your AppleScript launcher script to add `/usr/local/bin` to your `PATH` environment variable before calling `octave`. Or you could have it run a login bash shell (which should pick up your environment customizations) which then runs `octave --gui`. Or something like that.

Or you could try switching to Octave.app, which takes care of some of this stuff for you. :D If you want a nice Octave app icon in your /Applications folder like a regular native Mac app, that's exactly what we provide. We're stuck on Octave 6.2.0 currently, but I'm going to try rolling out 6.3.0 and 6.4.0 soon.

**Comment by Ken-Leo** [comment]
> Thanks Andrew! I'm running Octave through an applescript file which contains only: do shell script "/usr/local/bin/octave --gui" so as the GUI is launched and I can also have it like an Apple app in my Application folder. I guess I just have to add my /usr/local/bin to the PATH listed in the "system env" results, but I don't know which PATH it is (anyway, different from my own local PATH environment variable obtained when echoing it in a terminal). I'm ok to forward the discussion to the discourse group, but maybe it won't be necessary if you can tell me what PATH is listed within Octave and where/when it is defined.

I am getting into the same issue. So I just switch to Octave-6.3.0-beta1.dmg for installing. This works for me to install the   
control package successfully though there are warnings like:
`>> pkg install control-3.3.1.tar.gz

ld: warning: could not create compact unwind for _sb10yd_: stack subq instruction is too different from dwarf stack size
ld: warning: could not create compact unwind for _mb03xp_: stack subq instruction is too different from dwarf stack size
For information about changes from previous versions of the control package, run 'news control'.
>> 2021-12-11 10:24:53.167 octave-gui[6076:17898215] TSM AdjustCapsLockLEDForKeyTransitionHandling - _ISSetPhysicalKeyboardCapsLockLED Inhibit

>>
>> pkg list
Package Name  | Version | Installation directory
--------------+---------+-----------------------
     control  |   3.3.1 | /Users/kenleo/Library/Application Support/Octave.app/6.3.0/pkg/control-3.3.1
>>`

**Comment by apjanke** [comment]
Good!

Those "compact unwind" warnings are fine. You can just ignore them.
