### ISSUE TITLE
Octave.app freezing with a spinning “beachball” mouse cursor

### ISSUE THREAD

**Issue by syuhadazb** [octave-app/octave-app#242]
## Description

Replace this section with a description of the problem, including:
  * What you did: opening the octave app 
  * What you expected to happen: open the octave app
  * What actually happened: 
[Spindump.zip](https://github.com/octave-app/octave-app/files/10307669/Spindump.zip)

## Environment and Diagnostics

Please run `system env` in Octave.app, and copy & paste the output here:

```
[output goes here]
```

If your problem is weird, please also run `octave_app_diagnostic_dump` in Octave.app and attach its output file to this issue.

If your problem is Octave.app freezing with a spinning “beachball” mouse cursor, if you can, please take a spindump, zip it, and attach it to this issue. (To create a spindump, open Activity Monitor while Octave.app is frozen, select the `octave-gui` process, click the “gear” button in the upper left, and choose "Spindump".)

**Comment by fafa113000** [comment]
[Spindump.zip](https://github.com/octave-app/octave-app/files/10470777/Spindump.zip)
hello ,I have this issue, You can find Zip attach

**Comment by apjanke** [comment]
Closing this ticket as not enough info / specifics to reproduce, plus I and I think most users have moved on to newer macOS versions now.

Please try the recent [Octave.app 8.4.0 release](https://github.com/octave-app/octave-app/releases/tag/v8.4.0) and if you still have problems with that, re-open this issue or post a new one.
