### ISSUE TITLE
Buy the octave.app domain?

### ISSUE THREAD

**Issue by apjanke** [octave-app/octave-app#26]
Sigh. Somebody else has registered the octave.app domain, which may lead to unfortunate confusion, especially since Twitter and similar services parse “Octave.app” as a URL/domain and auto-link it to http://octave.app, which is wrong. They're not using the domain for anything; it's just parked.

The octave.app domain is [brokered by domainagents.com](https://domainagents.com/offers.php?domain=octave.app&code=hover), and their minimum bid is $199. No telling if that will actually result in a sale, though. Domain Agents smells fishy, too. No telling if they actually have an association with the domain owner, or if they're just a couple folks who know how to use `whois` and a phone.

`whois` info says it's registered through or owned by Google (the administrative and technical contacts point there), though all the Registrant location info is redacted, and the actual registrar is GoDaddy (bleh). I'll try these contacts first and see if I can get anywhere.

**Comment by schoeps** [comment]
This is indeed very annoying and I am also not a fan to support this system... However, if we have to then I am happy to contribute. We could give money to Octave via FSF and then ask them to buy the domain.

**Comment by apjanke** [comment]
Well. You can't say I didn't try.

<img width="527" alt="Screen Shot 2019-03-27 at 11 29 55 AM" src="https://user-images.githubusercontent.com/2618447/55089423-c2c2e080-5083-11e9-9502-7de483a701f3.png">

LOL. octave-app.org it is, I guess.
