### ISSUE TITLE
octave doesn't find nc-config in ubuntu 24-04

### ISSUE THREAD

**Issue by GabrielCazesBoezio** [octave-app/octave-app#298]
## Description

Replace this section with a description of the problem, including:
  * What you did

In octave, 

pkg install -verbose -forge netcdf

  * What you expected to happen

netcdf installled

instead, it occurred this: 

>> pkg install -verbose -forge netcdf
mkdir (/tmp/oct-gnpYEn)
untar (/tmp/netcdf-1.0.18-vwGrTR.tar.gz, /tmp/oct-gnpYEn)
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for gawk... no
checking for mawk... mawk
checking for a sed that does not truncate output... /bin/sed
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C++... yes
checking whether g++ accepts -g... yes
checking for g++ option to enable C++11 features... none needed
checking for mkoctfile... /snap/octave/306/bin/mkoctfile-7.1.0 --verbose
checking for nc-config... no
configure: error: nc-config not found

error: pkg: error running the configure script for netcdf
error: called from
    configure_make at line 101 column 9
    install at line 202 column 7
    pkg at line 603 column 9
  * What actually happened

nc-config not found despite installed:

## Environment and Diagnostics

Please run `system env` in Octave.app, and copy & paste the output here:

SNAP_INSTANCE_NAME=octave
PATH=/snap/octave/306/usr/sbin:/snap/octave/306/usr/bin:/snap/octave/306/sbin:/snap/octave/306/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/octave/306/libexec/octave/7.1.0/site/exec/x86_64-pc-linux-gnu:/snap/octave/306/libexec/octave/api-v57/site/exec/x86_64-pc-linux-gnu:/snap/octave/306/libexec/octave/site/exec/x86_64-pc-linux-gnu:/snap/octave/306/libexec/octave/7.1.0/exec/x86_64-pc-linux-gnu:/snap/octave/306/bin
INVOCATION_ID=6b5fb12a1a5e480b957403a428468884
SESSION_MANAGER=local/gabriel-MS-7817:@/tmp/.ICE-unix/2154,unix/gabriel-MS-7817:/tmp/.ICE-unix/2154
BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/octave_octave.desktop
GNOME_SETUP_DISPLAY=:1
SNAP_DATA=/var/snap/octave/306
XDG_MENU_PREFIX=gnome-
XDG_RUNTIME_DIR=/run/user/1000/snap.octave
DISPLAY=:0
LOCPATH=/snap/octave/306/usr/lib/locale
UNITSFILE=/snap/octave/306/usr/share/units/definitions.units
LANG=es_ES.UTF-8
XDG_CURRENT_DESKTOP=ubuntu:GNOME
XAUTHORITY=/run/user/1000/.mutter-Xwaylandauth.H35FW2
XDG_SESSION_DESKTOP=ubuntu
XMODIFIERS=@im=ibus
SNAP_ARCH=amd64
SNAP_COOKIE=ftMFargilLCoo9iqLjeZsq3v-93c_Rgrz7txBS3tnZEnH205tuTF
SNAP_USER_COMMON=/home/gabriel/snap/octave/common
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
GNUPLOT_DRIVER_DIR=/snap/octave/306/usr/lib/gnuplot
GNUPLOT_LUA_DIR=/snap/octave/306/usr/share/gnuplot/gnuplot/5.2/lua
SHELL=/bin/bash
GDMSESSION=ubuntu
PKG_CONFIG_SYSROOT_DIR=/snap/octave/306
QT_ACCESSIBILITY=1
SNAP_REEXEC=
SNAP_NAME=octave
GJS_DEBUG_OUTPUT=stderr
QT_IM_MODULE=ibus
PWD=/home/gabriel
SNAP_REAL_HOME=/home/gabriel
XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/etc/xdg
XDG_DATA_DIRS=/usr/share/ubuntu:/usr/share/gnome:/home/gabriel/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
SNAP=/snap/octave/306
SNAP_EUID=1000
HTTP_PROXY=
LC_NUMERIC=C
LINES=53
MEMORY_PRESSURE_WRITE=c29tZSAyMDAwMDAgMjAwMDAwMAA=
ans = 0
```
```

If your problem is weird, please also run `octave_app_diagnostic_dump` in Octave.app and attach its output file to this issue.

If your problem is Octave.app freezing with a spinning “beachball” mouse cursor, if you can, please take a spindump, zip it, and attach it to this issue. (To create a spindump, open Activity Monitor while Octave.app is frozen, select the `octave-gui` process, click the “gear” button in the upper left, and choose "Spindump".)

**Comment by GabrielCazesBoezio** [comment]
Sorry, I would like to to add to my previous post that in terminal; "which" indicates that nc-config is at /usr/bin,

gabriel@gabriel-MS-7817:~$ which nc-config
/usr/bin/nc-config

**Comment by apjanke** [comment]
Hi, @GabrielCazesBoezio!

This here "octave-app" repo on GitHub is for [Octave.app](https://octave-app.org/), a special "native Mac app" distribution of GNU Octave for macOS. Looks like you're running Linux here, and this is a regular Octave issue. For that, you want the regular GNU Octave maintainers. Please head on over to the [Octave Discourse](https://octave.discourse.group/) or [core Octave bug tracker on GNU Savannah](https://savannah.gnu.org/bugs/?group=octave) to report it and get some help.
