### ISSUE TITLE
no close button for files in editor

### ISSUE THREAD

**Issue by eflister** [octave-app/octave-app#31]
macports version has a little "x" button to close each file in the editor.

**Comment by apjanke** [comment]
So do we, as far as I can tell.

<img width="1005" alt="Screen Shot 2019-04-17 at 11 42 55 AM" src="https://user-images.githubusercontent.com/2618447/56301567-1023f200-6106-11e9-86b0-62cd37dfc401.png">


Can you post a screenshot of what yours looks like?

**Comment by apjanke** [comment]
Oh, wait, you're right: it's gone in 5.1.0 beta 3.

<img width="984" alt="Screen Shot 2019-04-17 at 11 45 47 AM" src="https://user-images.githubusercontent.com/2618447/56301747-6b55e480-6106-11e9-9631-7fcfef4e9d33.png">

That little blank area on the left of the buttons is an X – you can click it and the file will close – it's just not visible.

This is going to be a weird one to figure out. Perhaps related to us building against Qt 5.11, whereas MacPorts is building against 5.12? My vanilla Homebrewed Octave 5.1.0 that's built against Qt 5.12 is too freeze-y for me to check that.

**Comment by eflister** [comment]
hmm, a clue is that in the macports 5.1.0 it removes the 'x' from all but the currently selected file.  i think it's better to leave it on all of them so you can close files without having to switch to them.

**Comment by eflister** [comment]
just noticed in macports 5.1.0 it does show the 'x' for unselected tabs when you hover over them...

**Comment by apjanke** [comment]
Weird. No "X" for me in Octave.app 5.1.0 beta 3 when I hover over the tabs.

Other weird thing is that Octave.app 4.4.1 and 5.1.0 beta 3 were both built against the same Qt 5.11.2, yet Octave.app 4.4.1 shows the "X"s just fine, so this isn't just a new Qt bug that popped up. Don't know what changed.

Here's another screenshot for submitting upstream.

<img width="1211" alt="Screen Shot 2019-04-18 at 9 37 16 PM" src="https://user-images.githubusercontent.com/2618447/56400560-80279a80-6222-11e9-80ae-86c650333973.png">

**Comment by apjanke** [comment]
Upstream has a patch for this against default, and it looks good to me. The Xs are back.

<img width="619" alt="Screen Shot 2019-05-27 at 6 12 49 PM" src="https://user-images.githubusercontent.com/2618447/58440836-17e29900-80ab-11e9-9a4f-508029e7aba7.png">

**Comment by apjanke** [comment]
I can't find the upstream bug report for this on Savannah, but it looks like it's fixed now, so closing as fixed.
