### ISSUE TITLE
Does not open, "not responding"

### ISSUE THREAD

**Issue by A-i-Y-a** [octave-app/octave-app#36]
## Description

After installing and making sure I had the right JDK version, I opened Octave. Now, normally on a Mac after opening something from the Finder I would see the app icon "pop out" a bit, but with Octave, it doesn't pop up. I wait, and nothing happens. When I try to open it again, I get the message that Octave isn't responding. 

## Environment and Diagnostics

Please run `system env` in Octave.app, and copy & paste the output here:

```
None, because I can't open Octave.app.

```

**Comment by A-i-Y-a** [comment]
Later, when I go onto another account on my Mac (that I didn't install Octave from), I get stuck on the "Verifying 'Octave-4.4.1'" dialog, with the blue bar never going past 3/4 of the way.

**Comment by apjanke** [comment]
Hi @A-i-Y-a. Thanks for the bug report. Could you try the 5.1.0 beta3 download here and let us know if that works for you?

https://github.com/octave-app/octave-app/releases/download/v5.1.0-beta3/Octave-5.1.0-beta3.dmg

**Comment by apjanke** [comment]
Closing due to no response.

There are newer [6.2.0](https://github.com/octave-app/octave-app/releases/tag/v6.2.0) and [8.4.0](https://github.com/octave-app/octave-app/releases/tag/v8.4.0) releases out; give those a try if you're still having trouble.
