### ISSUE TITLE
Octave-4.4.1.app hangs on "verifying" at first launch, at ~2/3 completed ends

### ISSUE THREAD

**Issue by msw4chl** [octave-app/octave-app#39]
Install process goes well on MacOS 10.13.6 with dmg file into App folder, though it takes a long time!

Prior to above, place the jdk folder jdk-11.0.2.jdk/ in /Library/Java/JavaVirtualMachines

Then click on Octave...app from finder, right click to get popup menu, click Open

Wait over 30min while "verifying" step runs.  Gets to ~2/3 completed, and hangs. Completes after over an hour, and never has "beachball" and 0% CPU, no memory system resources used according to Activity Monitor.

Finally get a popup, and click "Open" to allow Octave to run. After another hour, still no window opens, nothing.

Any suggestions on what to do to allow Octave to completely launch? 

## Environment and Diagnostics

Please run `system env` in Octave.app, and copy & paste the output here:
 Can't get Octave.app going so unable to run this.
```
[output goes here]
```

**Comment by msw4chl** [comment]
Repeatedly launching Octave...app resulted in two more steps that apparently completed installation, then launcing a 3rd time, the Gui slowly launched and worked. Hmm, sure took a long time on MacOS!

**Comment by apjanke** [comment]
Hi @msw4chl! Sorry I didn't see this when first posted.

I'm afraid I'm not able to do much about this: Octave.app sometimes launches slow or not at all, and I haven't made any progress in identifying the cause or anything to do about it so far. I can't see a pattern in the machines of the users it's happened to.

If you wouldn't mind helping us collect some more data, could you try deleting Octave.app and reinstalling it, and then seeing if it's still slow? Is it slow on every launch for you, or does it seem to fix itself once it's finally able to open?
