### ISSUE TITLE
Package install errors

### ISSUE THREAD

**Issue by radlyeel** [octave-app/octave-app#4]
First, major congrats to the packaging team.  I just installed 4.4 beta, having had 4.0 (from macports) before.  This is MUCH better.  Thanks!  Now for my issue.

The first need I had was for the "butter" function, which is in the "signal" package, which in turn depends on "control".  When I ran "pkg install -forge control" I got a long stream of warnings that I don't get when I do the same thing on Ubuntu with version 4.3.  Is that just a temporary issue with the sourceforge package not being up to date?  Or might it be something on my Mac needing an update? Running "pkg install -forge signal" went cleanly, no warnings or issues, and everything seemed to run okay after the two packages were installed.  The tail of the warnings is attached (the command window wasn't big enough to hold the entire output).
[Octave_install_control.log](https://github.com/octave-app/octave-app/files/2342594/Octave_install_control.log)

**Comment by apjanke** [comment]
Thanks, radlyeel!

Those warnings are normal under Octave 4.4 and are not specific to Octave.app: the "control" package on Octave Forge has not been updated to take 4.4's new deprecations into account. (Note the "4.4" as the first argument to OCTAVE_DEPRECATED.) They're ugly, but you can ignore them as long as the `pkg install` command does not actually error out, which it doesn't look like it's doing in your case.

We should report this upstream to the maintainers of the "control" package. I think that would be the Octave issue tracker at https://savannah.gnu.org/bugs/?group=octave.

**Comment by apjanke** [comment]
Closing this out since it's not Octave.app-specific, and it's just warnings, not an actual error.

Please re-open if I've made a mistake here.
