### ISSUE TITLE
Text of axis and colorbar ticks are "too small" on displayed figures

### ISSUE THREAD

**Issue by falcolombardi64** [octave-app/octave-app#40]
Greetings

I have been reruning and improving my geosciences related scripts i did in matlab several years ago, I'm currently running the official Windows 32bit package in a old 2GHz core 2 duo with 2 GB of Ram. 

Now I have been using this octave 4.4.1 app in a more "recent" macbook with better specs, as downloaded from:

https://github.com/octave-app/octave-app/releases/download/v4.4.1/Octave-4.4.1.dmg

Most of my codes run exactly as they do in the official Octave Windows, except for the fact that the figures displayed in the mac app have the text of the axis ticks, not the labels (well if not specified the labels and titles are also displayed too small) and the colorbar ticks come as really small by default so they are almost unreadable, also they don't scale to bigger size if i make the figures bigger.  Using set and get commands on the axis and tick properties i can make the text from the axis bigger, but i haven't been able to do the same to the colorbar ones, anyone has an idea as to why the texts defaults to such tiny size?

Examples of this can be seen in this album where i have replicated examples from a package called m_map:

https://imgur.com/a/WctuUjx

They are also screenshots since the print  -dpng command is broken and crashes the app, for comparision the pngs exported from the Windows official release are in this album:

https://imgur.com/a/2yKbSXc

I'm still trying to figure what is the best format to export in this app but still is the most simple way to run a GUI Octave on Mac, thanks for your time.

## Environment and Diagnostics

```
>> system env
SHELL=/bin/bash
TERM=xterm
TMPDIR=/var/folders/kf/g0yjq51j22g6h4y8xkyrm0p80000gn/T/
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.7BmseWwyTk/Render
LC_NUMERIC=C
USER=Marci
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.tVFpN9y1P0/Listeners
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x56
COLUMNS=83
PATH=/Applications/Octave-4.4.1.app/Contents/Resources/usr/bin/:/Applications/Octave-4.4.1.app/Contents/Resources/usr/bin/:/usr/local/sbin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Users/janke/.rvm/bin:/Applications/Octave-4.4.1.app/Contents/Resources/usr/Cellar/octave-octave-app_4.4.1_0/4.4.1/libexec/octave/4.4.1/site/exec/x86_64-apple-darwin15.6.0:/Applications/Octave-4.4.1.app/Contents/Resources/usr/Cellar/octave-octave-app_4.4.1_0/4.4.1/libexec/octave/api-v52/site/exec/x86_64-apple-darwin15.6.0:/Applications/Octave-4.4.1.app/Contents/Resources/usr/Cellar/octave-octave-app_4.4.1_0/4.4.1/libexec/octave/site/exec/x86_64-apple-darwin15.6.0:/Applications/Octave-4.4.1.app/Contents/Resources/usr/Cellar/octave-octave-app_4.4.1_0/4.4.1/libexec/octave/4.4.1/exec/x86_64-apple-darwin15.6.0:/Applications/Octave-4.4.1.app/Contents/Resources/usr/Cellar/octave-octave-app_4.4.1_0/4.4.1/bin
_=/usr/bin/env
PWD=/Users/Marci
GS_OPTIONS=-sICCProfilesDir=/Applications/Octave-4.4.1.app/Contents/Resources/usr/opt/ghostscript_9.25_0/share/ghostscript//iccprofiles/ -sGenericResourceDir=/Applications/Octave-4.4.1.app/Contents/Resources/usr/opt/ghostscript_9.25_0/share/ghostscript//Resource/ -sFontResourceDir=/Applications/Octave-4.4.1.app/Contents/Resources/usr/opt/ghostscript_9.25_0/share/ghostscript//Resource/Font
LANG=es_MX.UTF-8
XPC_FLAGS=0x0
F77=/Applications/Octave-4.4.1.app/Contents/Resources/usr/bin/gfortran
LINES=16
XPC_SERVICE_NAME=0
HOME=/Users/Marci
SHLVL=2
FC=/Applications/Octave-4.4.1.app/Contents/Resources/usr/bin/gfortran
GNUTERM=qt
LOGNAME=Marci
DISPLAY=/private/tmp/com.apple.launchd.rAgRLF2vQa/org.macosforge.xquartz:0
LC_TIME=C
```

**Comment by apjanke** [comment]
Thanks for the bug report.

Is it possible for you to share some example plot-creating code that's showing this behavior, so I can reproduce it on my machine?

**Comment by apjanke** [comment]
Closing as stale: this was posted against 4.4, and we're up to working on the 9.x series now. Links in original post are 404 now, so hard for me to reproduce.

If this is still an issue with newer Octave.app releases like [8.4.0](https://github.com/octave-app/octave-app/releases/tag/v8.4.0) and [9.2.0 beta1](https://github.com/octave-app/octave-app/releases/tag/v9.2.0_beta1), please re-open this ticket and comment with some details.
