### ISSUE TITLE
Download of Octave app for Mac too slow

### ISSUE THREAD

**Issue by dvasal** [octave-app/octave-app#41]
The download of the octave app is too slow. It is showing me it will take 24 hours to download the 862 MB file where I am easily able to download other stuff at more than 3MB/s.

**Comment by apjanke** [comment]
The Octave.app releases are hosted on GitHub Releases, which has a pretty good bandwidth. Not much we can do about this.

Download speeds are fine for me. I'm guessing it's a local CDN issue or something in your area of the network? Try the download again tomorrow and see if it's fixed.

In the mean time, here's an alternate download link to get you up and running: https://www.dropbox.com/s/kzqx6cjeob4qwyx/Octave-4.4.1.dmg?dl=0. This is from Dropbox, so hopefully it won't be affected by whatever's causing the slow download from GitHub for you.

**Comment by dvasal** [comment]
Thanks a lot!

**Comment by apjanke** [comment]
Is the download still slow for you now?

**Comment by dvasal** [comment]
No it's good now.
Thanks for checking back.
Best
Deepanshu

**Comment by apjanke** [comment]
Cool. Closing as fixed.
