### ISSUE TITLE
Relocatable app

### ISSUE THREAD

**Issue by apjanke** [octave-app/octave-app#52]
Currently, the app only runs if it is installed in the default `/Applications/Octave.app` location. It would be nice if it were relocatable, so you could rename it or move it to other directories, and it would still run.

Low priority.

**Comment by mimenard** [comment]
Hello, just a quit comment because I'm interested by this feature. I usually move some big development applications in an external drive in order to prevent to fill my ssd. I hope someone would find a solution to make it possible. 
Is the problem related to usage of hardcoded path instead of relative somewhere?

**Comment by apjanke** [comment]
> Is the problem related to usage of hardcoded path instead of relative somewhere?

Exactly. Primarily in the linkage of dynamic libraries in the various packages that make up Octave.app. And since Octave.app has a lot of component packages, it's a nontrivial fix.

You miiiiiiight be able to get this to work as is by putting Octave.app on your external drive and then symlinking `/Applications/Octave.app` to it and running through the symlink; give that a try!

**Comment by apjanke** [comment]
After a couple more years experience, this looks hopeless to me. Closing as Wontfix.

**Comment by apjanke** [comment]
Sorry. I feel you, but I think this is kind of "baked in" to the basic infrastructure of how Octave.app is built. (It's basically a macOS app bundle wrapper on top of a [Homebrew](https://brew.sh/) installation to a nonstandard "prefix" location.) Maybe a solvable problem, but likely not something I have the time and skill to tackle myself.

If it's any consolation, the Octave.app 8.4.0 build cuts the app size in half or so, as of the [alpha3 build](https://github.com/octave-app/octave-app/releases/tag/v8.4.0_alpha3).
