### ISSUE TITLE
4.4.0 RC1 version crashes on startup on OSX El Capitan

### ISSUE THREAD

**Issue by yannig27** [octave-app/octave-app#6]
on
MacBook Pro (Retina, 13 pouces, end 2013)
2.4 GHz Intel Core i5 processor
4 Go 1600 MHz DDR3 memory

nothing else needs to be said more, at this point

**Comment by larrywesterman** [comment]
Same problem, using Mac mini, 2.6 GHz Intel Core i5, 8 GB 1600 MHz DDR3 RAM

If I run the applet in a terminal window, I get the error:
NSDocumentController Info.plist warning: The values of CFBundleDocumentTypes entries must be arrays.

**Comment by larrywesterman** [comment]
Relevant portion of Info.plist file reads:
	<key>CFBundleDocumentTypes</key>
	<dict>
		<key>CFBundleTypeExtensions</key>
		<array>
			<string>m</string>
		</array>
		<key>CFBundleTypeOSTypes</key>
		<array>
			<string>Mfile</string>
		</array>
		<key>CFBundleTypeRole</key>
		<string>Editor</string>
	</dict>

**Comment by larrywesterman** [comment]
The relevant portion of the Info.plist file reads:

	<key>CFBundleDocumentTypes</key>
	<dict>
		<key>CFBundleTypeExtensions</key>
		<array>
			<string>m</string>
		</array>
		<key>CFBundleTypeOSTypes</key>
		<array>
			<string>Mfile</string>
		</array>
		<key>CFBundleTypeRole</key>
		<string>Editor</string>
	</dict>

**Comment by hfogel** [comment]
> Same problem, using Mac mini, 2.6 GHz Intel Core i5, 8 GB 1600 MHz DDR3 RAM
> 
> If I run the applet in a terminal window, I get the error:
> NSDocumentController Info.plist warning: The values of CFBundleDocumentTypes entries must be arrays.

I'm getting the same error using El Capitan (10.11.6) on a mid-2013 MacBook Air

**Comment by apjanke** [comment]
Do you have any crash dump files in `~/Library/Logs/DiagnosticReports` for octave? If so, could you post one? I'm wondering if this is the same CPU-architecture-dependent "Illegal Instruction: 4" crash seen in #3.

**Comment by yannig27** [comment]
I already gone back to an older version, (and erased de 4.40 RC1)...

**Comment by apjanke** [comment]
No worries; thanks for the bug report.

**Comment by hfogel** [comment]
Here is one of my crash dump files:

[octave-gui_2018-10-07-135209_Hannahs-MacBook-Air-2.crash.zip](https://github.com/octave-app/octave-app/files/2473407/octave-gui_2018-10-07-135209_Hannahs-MacBook-Air-2.crash.zip)

**Comment by apjanke** [comment]
Thanks @hfogel.

That looks like #3.

**Comment by apjanke** [comment]
@larrywesterman 

> If I run the applet in a terminal window, I get the error:
> ...

How did you run the application in the terminal window such that you could see that error message? I'm trying `open -a Octave-4.4.0.app` and it launches but I don't see any error or warning messages.

**Comment by apjanke** [comment]
@larrywesterman 

Oh, never mind. Found it.

```
[/Applications/Octave-4.4.0.app]
$ ./Contents/MacOS/applet
2018-10-16 01:31:46.220 applet[52468:23680097] NSDocumentController Info.plist warning: The values of CFBundleDocumentTypes entries must be arrays.
```

**Comment by apjanke** [comment]
I'm closing this issue as a duplicate. I think the crash and the Info.plist format warning are unrelated issues.

The crash is handled in #3. There's a new beta10 build out that fixes it; see details there. (yannig27's Late 2013 MacBook Pro is a Haswell, which is consistent with #3's crash behavior.  hfogel's Mid 2013 MacBook Air is probably Haswell or earlier too, though I can't verify that on Wikipedia.)

The Info.plist warning message is handled in #8.
