### ISSUE TITLE
Hang in test suite on 4.4.0 beta2: "'.../@ftp/dir.m' has been modified by another application"

### ISSUE THREAD

**Issue by apjanke** [octave-app/octave-app#69]
A long way in to running the test suite in the GUI, it switches to the editor and pops up this dialog. The dialog is unresponsive, so this effectively hangs Octave.

<img width="581" alt="screen shot 2018-06-23 at 4 42 20 am" src="https://user-images.githubusercontent.com/2618447/41807659-f59ad72e-769f-11e8-87d2-896984773eb8.png">

This is with the Ghostscript fix and the [Qt patch to remove FSEventStreamFlushSync()](FSEventStreamFlushSync()) applied.

The files `dir.m`, `set.m`, `quantile.m`, and `ls.m` are open in the editor when this happened. I didn't start out with any files open in the editor.

**Comment by PRUBHTEJ** [comment]
@apjanke, I'm also facing the same issue. Is there any way to resolve it?

**Comment by apjanke** [comment]
@PRUBHTEJ Can you try the new 6.0.90 Release Candidate beta and see if it happens there? https://github.com/octave-app/octave-app/releases/tag/v6.0.90-rc1

We're far enough behind upstream's releases now that I'm kind of dubious about getting more fixes into the 4.x series.

**Comment by PRUBHTEJ** [comment]
Sure!!
Just to let you know, I'm facing the same issue with 5.x beta as well.

**Comment by apjanke** [comment]
Closing this ticket since 4.x is basically EOL now; focusing on 6.x and 8.x; see https://github.com/octave-app/octave-app/issues/243.
