### ISSUE TITLE
Crash running 4.4.1 on Mac OS X 10.13.6

### ISSUE THREAD

**Issue by larrywesterman** [octave-app/octave-app#7]
Was able to install and run Octave 4.4.1 on Mac OS X; could execute several Matlab files given by third party. However, 4.4.1 crashes executing several files reported to execute properly using 4.2.x on Mac OS X. Attached is crash dump.  This is after vanilla installation using 'sudo port install octave'.
[OctaveCrashDump.txt](https://github.com/octave-app/octave-app/files/2466123/OctaveCrashDump.txt)

**Comment by apjanke** [comment]
Hi larrywesterman.

I think this might be the wrong place for this bug report. This repo is for Octave.app specifically; not for the MacPorts packaging of Octave, or Octave itself. (We're not even on 4.4.1 yet.) I think you need to report this either to MacPorts or to Octave itself, using the [octave-help mailing list](https://lists.gnu.org/mailman/listinfo/help-octave).

**Comment by apjanke** [comment]
Closing this as off-topic. Please re-open if it turns out you are in fact running Octave.app and not a different distribution/installation of Octave.
